import { DEFAULT_OUTPUT } from "./identity";
import type { AutofixGroupDefinition, ToolDefinition, ToolField } from "./types";

export const AUTOFIX_GROUPS: AutofixGroupDefinition[] = [
  {
    id: "travel",
    name: "Travel & Outdoors",
    description: "Beach, mountains, sunset and night. Tick only the extras you want.",
  },
  {
    id: "urban",
    name: "Urban & Architecture",
    description: "Landmarks, streets, interiors and glass. People stay unless you tick removal.",
  },
  {
    id: "events",
    name: "Events & Portraits",
    description: "Concerts, group shots and pets. Faces are not invented.",
  },
  {
    id: "food",
    name: "Food & Dining",
    description: "Clean the table, not the recipe. Food stays as plated.",
  },
  {
    id: "fashion",
    name: "Fashion & Style",
    description: "Outfit and mirror polish. Fit and identity stay.",
  },
  {
    id: "vehicles",
    name: "Automotive & Vehicles",
    description: "Showcase the car. Shape, colour and badges stay.",
  },
  {
    id: "weather",
    name: "Weather & Atmosphere",
    description: "Sky and light changes that still match the scene.",
  },
  {
    id: "celebrations",
    name: "Celebrations & Weddings",
    description: "Stage and venue tidy-up. People stay themselves.",
  },
  {
    id: "ecommerce",
    name: "E-commerce & Online Selling",
    description: "Studio-ready products. The item is never redesigned.",
  },
  {
    id: "documents",
    name: "Documents & Practical Fixes",
    description: "Readable scans. Text, numbers and logos stay exact.",
  },
  {
    id: "garden",
    name: "Garden & Still Life",
    description: "Planters, borders and table-top still life. Plants stay themselves.",
  },
];

function toggles(options: string[]): ToolField {
  return {
    id: "selected",
    label: "Optional fixes",
    type: "toggles",
    help: "Autofix always applies the base improvement. Tick extras. Removals only happen if you tick them.",
    fallback:
      "none — apply only the base improvement. Do not remove people, vehicles or objects.",
    options: options.map((label) => ({ value: label, label })),
  };
}

export const AUTOFIX_TOOLS: ToolDefinition[] = [
  {
    id: "beach-autofix",
    category: "autofix",
    autofixGroup: "travel",
    name: "Beach Scene Autofix",
    shortDescription: "Holiday colour, clearer water, balanced sun.",
    icon: "sun",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "People and objects stay unless you tick a removal. Colours stay natural.",
    fields: [
      toggles([
        "Make sky naturally bluer",
        "Make sea naturally bluer",
        "Improve water clarity",
        "Improve sand and shoreline",
        "Balance harsh sunlight",
        "Lift dark foreground shadows",
        "Remove unwanted people from beach",
        "Remove beach litter",
        "Remove distracting objects",
        "Reduce haze",
        "Improve overall holiday colour",
      ]),
    ],
    mainPrompt:
      "Automatically improve this beach photograph while preserving the original composition, important subjects, natural lighting, and realistic appearance. Improve the sky and sea with natural blue tones, enhance water clarity and detail, balance exposure, lift harsh shadows, and improve the overall holiday atmosphere. Do not make colours overly saturated or artificial.\n\nApply only the selected optional fixes:\n{{selected}}\n\nIf removing people or objects, reconstruct the affected areas naturally using the surrounding beach, sand, water, sky, and scenery. Preserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "mountain-haze-autofix",
    category: "autofix",
    autofixGroup: "travel",
    name: "Mountain & Forest Haze",
    shortDescription: "Clear distant haze. Keep the atmosphere.",
    icon: "mountain",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not invent mountain or forest detail. Hikers stay unless you tick removal.",
    fields: [
      toggles([
        "Reduce distant haze",
        "Improve mountain detail",
        "Boost natural forest greens",
        "Improve sky clarity",
        "Remove stray hikers",
        "Remove trail markers",
        "Improve foreground exposure",
        "Preserve natural atmosphere",
      ]),
    ],
    mainPrompt:
      "Automatically improve this mountain or forest photograph while preserving the original composition, important subjects and natural atmosphere. Reduce haze only as selected, recover reasonable distant detail, and keep colours realistic. Do not invent scenery that is not supported by the original image.\n\nApply only the selected optional fixes:\n{{selected}}\n\nIf removing people or markers, reconstruct the area from surrounding rock, trees, path and sky. Preserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "sunset-autofix",
    category: "autofix",
    autofixGroup: "travel",
    name: "Sunset & Golden Hour",
    shortDescription: "Warmer sky, lifted foreground, still the same evening.",
    icon: "sun",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not turn dusk into a different time of day. People stay unless you tick removal.",
    fields: [
      toggles([
        "Improve sunset colours",
        "Enhance horizon gradients",
        "Lift dark foreground subjects",
        "Remove power lines",
        "Remove lens flares",
        "Improve reflections",
        "Balance warm/cool tones",
      ]),
    ],
    mainPrompt:
      "Automatically improve this sunset or golden-hour photograph while preserving the original composition, important subjects and time of day. Strengthen natural warm colour and horizon light without making it artificial.\n\nApply only the selected optional fixes:\n{{selected}}\n\nIf removing power lines or flares, reconstruct the sky and scenery naturally. Preserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "night-astro-autofix",
    category: "autofix",
    autofixGroup: "travel",
    name: "Night & Astrophotography",
    shortDescription: "Cleaner night sky. No invented stars.",
    icon: "moon",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not invent stars, the Milky Way or scenery that is not in the photograph.",
    fields: [
      toggles([
        "Reduce high-ISO noise",
        "Reduce yellow light pollution",
        "Improve sky detail",
        "Sharpen stars naturally",
        "Remove plane streaks",
        "Remove satellite streaks",
        "Improve foreground exposure",
        "Preserve night atmosphere",
      ]),
    ],
    mainPrompt:
      "Automatically improve this night or astrophotography image while preserving the original composition, important subjects and night atmosphere. Reduce noise and recover reasonable sky and foreground detail. Do not invent stars, nebulae or scenery that are not reasonably supported by the original image.\n\nApply only the selected optional fixes:\n{{selected}}\n\nIf removing plane or satellite streaks, reconstruct the sky naturally from neighbouring stars and colour. Preserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "city-landmark-autofix",
    category: "autofix",
    autofixGroup: "urban",
    name: "City Landmark Cleaner",
    shortDescription: "Tidy a landmark. Buildings and people stay.",
    icon: "landmark",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Buildings and people stay unless you tick a removal. No invented architecture.",
    fields: [
      toggles([
        "Remove construction cranes",
        "Remove scaffolding",
        "Remove pavement litter",
        "Remove temporary objects",
        "Remove unwanted signs",
        "Correct vertical building perspective",
        "Straighten buildings",
        "Improve architectural detail",
        "Balance exposure",
      ]),
    ],
    mainPrompt:
      "Automatically improve this city or landmark photograph while preserving buildings, people and important objects unless they are specifically selected for removal. Keep the architecture recognisable. When removing cranes, scaffolding, litter, signs or temporary objects, reconstruct the affected area naturally using surrounding architecture, sky, pavement and textures.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "road-street-autofix",
    category: "autofix",
    autofixGroup: "urban",
    name: "Road & Street Cleanup",
    shortDescription: "Clean a road photograph. Traffic signs stay unless ticked.",
    icon: "car",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Do not remove traffic signs that explain the road unless you tick that option.",
    fields: [
      toggles([
        "Remove road signs",
        "Remove temporary road signs",
        "Remove distracting street furniture",
        "Remove telegraph poles",
        "Remove utility poles",
        "Remove overhead wires",
        "Remove road litter",
        "Remove parked vehicles",
        "Correct road perspective",
        "Improve sky",
        "Improve road and landscape detail",
      ]),
    ],
    mainPrompt:
      "Automatically improve this road or street photograph while preserving the original composition and important subjects. Do not remove traffic signs that are important to understanding the road scene unless they are explicitly selected. Reconstruct removed items from surrounding tarmac, verge, sky and landscape.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "real-estate-autofix",
    category: "autofix",
    autofixGroup: "urban",
    name: "Real Estate & Interiors",
    shortDescription: "Straighter walls, balanced windows, quieter rooms.",
    icon: "house",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not restyle the room or invent furniture. Clutter only if you tick it.",
    fields: [
      toggles([
        "Correct wide-angle wall bowing",
        "Straighten vertical lines",
        "Balance bright windows",
        "Lift dark interior shadows",
        "Remove wall outlets",
        "Remove exposed cables",
        "Improve room lighting",
        "Correct colour cast",
        "Reduce distracting clutter",
      ]),
    ],
    mainPrompt:
      "Automatically improve this real-estate or interior photograph while preserving the room, furniture and important objects unless they are selected for removal. Correct geometry and exposure naturally. Do not restyle the interior or invent furniture.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "glass-reflection-autofix",
    category: "autofix",
    autofixGroup: "urban",
    name: "Glass & Reflection Eraser",
    shortDescription: "See through museum glass, aquariums and windows.",
    icon: "droplets",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not invent what is behind the glass if it cannot reasonably be recovered.",
    fields: [
      toggles([
        "Reduce museum glass glare",
        "Reduce aquarium reflections",
        "Reduce vehicle-window reflections",
        "Reduce unwanted reflections",
        "Improve visibility through glass",
      ]),
    ],
    mainPrompt:
      "Automatically improve visibility through glass in this photograph while preserving the original subject and important details. Reduce glare and reflections only as selected. Do not invent details that cannot reasonably be recovered from the original image.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "concert-night-autofix",
    category: "autofix",
    autofixGroup: "events",
    name: "Concert & Night Out",
    shortDescription: "Fix stage colour. Keep the atmosphere.",
    icon: "music",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not flatten concert lighting into daylight. Faces stay the same people.",
    fields: [
      toggles([
        "Correct red stage lighting",
        "Correct blue stage lighting",
        "Improve skin tones",
        "Reduce harsh spotlight halos",
        "Improve exposure",
        "Preserve concert atmosphere",
        "Reduce distracting background lights",
      ]),
    ],
    mainPrompt:
      "Automatically improve this concert or night-out photograph while preserving the original composition, people, and live atmosphere. Correct coloured stage light only as selected and keep skin tones believable. Do not turn the scene into studio lighting.\n\nApply only the selected optional fixes:\n{{selected}}\n\nDo not invent or replace faces. Preserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "group-shot-autofix",
    category: "autofix",
    autofixGroup: "events",
    name: "Group Shot Polish",
    shortDescription: "Open eyes, even flash, same people.",
    icon: "images",
    identityPreservation: "strict",
    version: 1,
    active: true,
    extraImages: 2,
    note: "Add extra burst frames if you have them. They are only used to help open closed eyes. Faces are never invented.",
    fields: [
      toggles([
        "Fix closed eyes",
        "Reduce eyeglass reflections",
        "Balance flash shadows",
        "Improve facial exposure",
        "Improve sharpness",
        "Remove distracting background objects",
      ]),
    ],
    mainPrompt:
      "Automatically improve this group photograph while preserving every person’s identity, expression, pose, clothing and body proportions. If additional burst frames are supplied, use them only when appropriate to help correct closed eyes. Do not invent or replace faces.\n\nApply only the selected optional fixes:\n{{selected}}\n\nIf removing background objects, reconstruct from the surrounding scene. Preserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "pet-portrait-autofix",
    category: "autofix",
    autofixGroup: "events",
    name: "Pet Portrait Enhancer",
    shortDescription: "Fur, eyes and a quiet background. Same animal.",
    icon: "paw",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Leash, collar and harness only come off if you tick them. The pet is not a different animal.",
    fields: [
      toggles([
        "Remove leash",
        "Remove collar",
        "Remove harness",
        "Remove debris from fur",
        "Improve eye catchlights",
        "Improve fur detail",
        "Improve exposure",
        "Remove distracting background objects",
      ]),
    ],
    mainPrompt:
      "Automatically improve this pet portrait while preserving the animal’s identity, markings, pose and proportions. Do not turn it into a different pet. Reconstruct removed kit from surrounding fur, grass or flooring.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "gourmet-plate-autofix",
    category: "autofix",
    autofixGroup: "food",
    name: "Gourmet Plate Cleanup",
    shortDescription: "Crumbs and lighting, not a new dish.",
    icon: "utensils",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not change the food, portion, plating or ingredients. Keep colour realistic.",
    fields: [
      toggles([
        "Remove table crumbs",
        "Remove sauce smudges",
        "Remove water spots from cutlery",
        "Correct yellow restaurant lighting",
        "Improve food colour",
        "Improve exposure",
        "Reduce background clutter",
        "Improve food detail",
      ]),
    ],
    mainPrompt:
      "Automatically improve this food photograph while preserving the actual food, portion size, plating and ingredients. Do not alter what was served unless an optional fix explicitly asks for a surface clean. Keep colours realistic and avoid excessive saturation.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "outfit-mirror-autofix",
    category: "autofix",
    autofixGroup: "fashion",
    name: "Outfit & Mirror Selfie Polish",
    shortDescription: "Lint, tags and smudges. Same person, same fit.",
    icon: "shirt",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Preserves clothing fit, body proportions, identity, pose and original appearance.",
    fields: [
      toggles([
        "Smooth heavy clothing wrinkles",
        "Remove lint",
        "Remove dust",
        "Remove hanging price tags",
        "Remove phone smudges from mirrors",
        "Remove water spots from mirrors",
        "Improve lighting",
        "Improve overall clarity",
      ]),
    ],
    mainPrompt:
      "Automatically improve this outfit or mirror-selfie photograph while preserving clothing fit, body proportions, identity, pose and original appearance. Do not slim, reshape or beautify the person. Do not redesign the clothes.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "car-showcase-autofix",
    category: "autofix",
    autofixGroup: "vehicles",
    name: "Car Showcase",
    shortDescription: "Clean paint and glass. The car stays this car.",
    icon: "car",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Never changes shape, wheels, badges, colour or identifying features unless you ask.",
    fields: [
      toggles([
        "Blur licence plate",
        "Replace licence plate with neutral plate",
        "Remove bug splatters from windscreen",
        "Remove bug splatters from bumper",
        "Remove photographer reflections",
        "Improve paintwork reflections",
        "Improve lighting",
        "Improve vehicle detail",
      ]),
    ],
    mainPrompt:
      "Automatically improve this vehicle photograph while preserving the exact vehicle shape, wheels, badges, colour and important identifying features. Do not redesign the car. Licence-plate changes only if selected.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "overcast-sunlight-autofix",
    category: "autofix",
    autofixGroup: "weather",
    name: "Overcast-to-Sunlight Swap",
    shortDescription: "A believable blue sky and matching light.",
    icon: "cloud",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "New light must stay physically consistent across the whole scene.",
    fields: [
      toggles([
        "Replace flat grey sky with natural blue sky",
        "Add soft clouds",
        "Add warm sunlight",
        "Re-light foreground shadows",
        "Improve ambient tones",
        "Correct colour temperature",
        "Improve overall clarity",
      ]),
    ],
    mainPrompt:
      "Automatically improve this overcast photograph. If changing the sky or adding sunlight, keep the new lighting physically consistent across the whole scene, including shadows, reflections, colour temperature and foreground. Do not invent a different location.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "event-stage-autofix",
    category: "autofix",
    autofixGroup: "celebrations",
    name: "Event & Stage Cleanup",
    shortDescription: "Tidy the venue. Keep the people.",
    icon: "sparkles",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Preserves faces, identity, expressions, clothing and body proportions.",
    fields: [
      toggles([
        "Remove emergency exit signs",
        "Remove microphone stands",
        "Remove venue staff from background",
        "Remove distracting background objects",
        "Reduce stray hair flyaways",
        "Reduce visible tan lines",
        "Improve lighting",
        "Improve overall clarity",
      ]),
    ],
    mainPrompt:
      "Automatically improve this event, wedding or stage photograph while preserving faces, identity, expressions, clothing and body proportions. Do not beautify or reshape people. Reconstruct removed venue clutter from surrounding scenery.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "product-studio-autofix",
    category: "autofix",
    autofixGroup: "ecommerce",
    name: "Product Studio Prep",
    shortDescription: "Clean backdrop. The product is not redesigned.",
    icon: "shoppingBag",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "The product must never be redesigned or subtly changed. Shape, colour, logo and branding stay exact.",
    fields: [
      toggles([
        "Replace cluttered desk background",
        "Replace cluttered floor background",
        "Add seamless studio backdrop",
        "Add soft drop shadow",
        "Remove fingerprints",
        "Remove dust",
        "Remove metallic surface smudges",
        "Remove plastic surface smudges",
        "Remove glass surface smudges",
        "Improve product lighting",
      ]),
    ],
    mainPrompt:
      "Automatically prepare this product photograph for listing while preserving the exact product shape, proportions, colour, logo, branding and important details. The product must never be redesigned or subtly changed.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "whiteboard-document-autofix",
    category: "autofix",
    autofixGroup: "documents",
    name: "Whiteboard & Document Scan",
    shortDescription: "Flatter, clearer, still the same writing.",
    icon: "fileText",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not rewrite, reinterpret or invent text, diagrams or handwriting.",
    fields: [
      toggles([
        "Correct perspective",
        "Flatten page curvature",
        "Remove phone shadow",
        "Remove hand shadow",
        "Reduce glare",
        "Improve text contrast",
        "Clean background",
        "Convert to clean black and white",
        "Improve readability",
      ]),
    ],
    mainPrompt:
      "Automatically improve this whiteboard, document, or paper photograph. Correct perspective, flatten page curvature, remove unwanted phone or hand shadows, reduce glare, and improve text contrast.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all text, diagrams, handwriting, and important information accurately. Do not rewrite, reinterpret, or invent text.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "receipt-paperwork-autofix",
    category: "autofix",
    autofixGroup: "documents",
    name: "Receipt & Paperwork Cleanup",
    shortDescription: "Straight, readable, numbers unchanged.",
    icon: "fileText",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Never alter dates, prices, numbers, names, logos or other document content.",
    fields: [
      toggles([
        "Correct perspective",
        "Remove shadows",
        "Reduce glare",
        "Improve readability",
        "Clean background",
        "Improve contrast",
        "Straighten document",
      ]),
    ],
    mainPrompt:
      "Automatically improve this receipt or paperwork photograph so it is straight, even and readable. Never alter dates, prices, numbers, names, logos or other document content.\n\nApply only the selected optional fixes:\n{{selected}}\n\nPreserve all unselected subjects and details. Do not rewrite or invent text.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "garden-still-life-autofix",
    category: "autofix",
    autofixGroup: "garden",
    name: "Garden & Still Life Autofix",
    shortDescription: "Clearer plants and planters. Species stay.",
    icon: "mountain",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Does not change plant species, rearrange beds or invent flowers.",
    fields: [
      toggles([
        "Soften harsh noon light",
        "Lift dark foliage",
        "Improve plant detail",
        "Correct colour cast",
        "Improve sky",
        "Reduce empty-pot clutter",
        "Remove hose or watering can",
        "Remove distracting objects",
      ]),
    ],
    mainPrompt:
      "Automatically improve this garden or still-life photograph. Balance exposure, recover foliage detail and keep colours natural.\n\nApply only the selected optional fixes:\n{{selected}}\n\nDo not change plant species, invent flowers, rearrange the garden or alter people. Preserve all unselected subjects and details.",
    outputFormat: DEFAULT_OUTPUT,
  },
];
