import { DEFAULT_OUTPUT } from "./identity";
import type { ClothingGroupDefinition, ToolDefinition, ToolField } from "./types";

export const CLOTHING_GROUPS: ClothingGroupDefinition[] = [
  {
    id: "swap",
    name: "Clothing Swap",
    description: "Replace, recolour or restyle clothes. The person stays the same.",
  },
  {
    id: "play",
    name: "Swimwear, Lingerie & Costume",
    description: "Beachwear, underwear and fancy dress. Face, pose and body stay.",
  },
  {
    id: "extras",
    name: "Accessories & Footwear",
    description: "Hats, bags, socks and shoes. Nothing else moves.",
  },
  {
    id: "builder",
    name: "Outfit Builder",
    description: "Build a look from pieces, or describe the whole outfit.",
  },
];

const who: ToolField = {
  id: "who",
  label: "Which person",
  type: "text",
  placeholder: "e.g. the person on the left",
  fallback: "the main person in the photograph",
};

export const CLOTHING_TOOLS: ToolDefinition[] = [
  {
    id: "clothing-swap",
    category: "clothing",
    clothingGroup: "swap",
    name: "Clothing Swap",
    shortDescription: "Replace the outfit. Same person, same pose.",
    icon: "shirt",
    identityPreservation: "strict",
    version: 1,
    active: true,
    example: "T-shirt to shirt, jeans to shorts, casual clothes to a suit.",
    fields: [
      who,
      {
        id: "outfit",
        label: "New outfit",
        type: "textarea",
        required: true,
        placeholder: "e.g. a navy suit over a white shirt, leather jacket over the same tee",
      },
    ],
    mainPrompt:
      "Replace the existing clothing on {{who}} with this outfit: {{outfit}}. Preserve face, identity, hairstyle, body proportions, pose, expression and skin tone. Make the new clothing realistically follow the body, pose, lighting, shadows and perspective. Do not change the background or other people.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "clothing-colour",
    category: "clothing",
    clothingGroup: "swap",
    name: "Clothing Colour",
    shortDescription: "Recolour one garment. Keep the fabric.",
    icon: "palette",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      who,
      {
        id: "garment",
        label: "Garment",
        type: "text",
        required: true,
        placeholder: "e.g. the jumper, the dress, the jacket",
      },
      {
        id: "colour",
        label: "New colour",
        type: "text",
        required: true,
        placeholder: "e.g. rust red, sage green, navy",
      },
    ],
    mainPrompt:
      "Change only the colour of this garment on {{who}}: {{garment}} becomes {{colour}}. Preserve fabric texture, folds, stitching, shadows, lighting and garment shape. Do not change the person, other clothes, pose or background.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "clothing-style",
    category: "clothing",
    clothingGroup: "swap",
    name: "Clothing Style",
    shortDescription: "A new style of clothes. Same recognisable person.",
    icon: "shirt",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      who,
      {
        id: "style",
        label: "New style",
        type: "textarea",
        required: true,
        placeholder: "e.g. relaxed smart-casual linen, 1990s denim, tailored workwear",
      },
    ],
    mainPrompt:
      "Restyle the clothing on {{who}} to this style: {{style}}. Keep the person recognisable. Preserve face, identity, hairstyle, body proportions, pose, expression and skin tone. Do not change the background.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "swimwear",
    category: "clothing",
    clothingGroup: "play",
    name: "Swimwear",
    shortDescription: "Realistic beachwear on the same person and pose.",
    icon: "droplets",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      who,
      {
        id: "suit",
        label: "Swimwear",
        type: "select",
        defaultValue: "swim shorts",
        options: [
          { value: "swim shorts", label: "Swim shorts" },
          { value: "swimming trunks", label: "Swimming trunks" },
          { value: "a bikini", label: "Bikini" },
          { value: "a one-piece swimsuit", label: "Swimsuit" },
          { value: "a rash vest and board shorts", label: "Rash vest" },
          { value: "casual beachwear", label: "Beachwear" },
        ],
      },
    ],
    mainPrompt:
      "Dress {{who}} in {{suit}} as a realistic photograph. Preserve identity, face, hairstyle, body proportions, pose, expression and skin tone. Keep the original setting unless it is clearly indoor clothing in an indoor room, in which case a simple beach or poolside setting is allowed. No beautification.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "underwear-lingerie",
    category: "clothing",
    clothingGroup: "play",
    name: "Underwear & Lingerie",
    shortDescription: "Underwear, lingerie or a playful look. Same person, same pose.",
    icon: "shirt",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Clothes change only. No nude option. Identity, pose and body stay as photographed.",
    fields: [
      who,
      {
        id: "look",
        label: "Look",
        type: "select",
        defaultValue: "everyday underwear",
        options: [
          { value: "everyday underwear", label: "Everyday underwear" },
          { value: "matching underwear set", label: "Matching set" },
          { value: "classic lingerie", label: "Lingerie" },
          { value: "silk or satin loungewear", label: "Silk loungewear" },
          { value: "a playful party outfit", label: "Playful / party" },
          { value: "a custom look described below", label: "Custom" },
        ],
      },
      {
        id: "detail",
        label: "Colour or extra detail",
        type: "text",
        placeholder: "e.g. black lace, cream silk, navy cotton",
        fallback: "colours and fabrics that suit the person and the photograph",
      },
    ],
    mainPrompt:
      "Change only the clothing on {{who}} to {{look}}. Extra detail: {{detail}}. Keep it a realistic photograph of the same adult. Preserve face, identity, hairstyle, body proportions, pose, expression and skin tone. Keep the original setting. Do not nude, do not beautify, do not change pose into a different scene, and do not alter other people or the background.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "remove-accessories",
    category: "clothing",
    clothingGroup: "extras",
    name: "Remove Accessories",
    shortDescription: "Hats, bags, glasses, jewellery — then rebuild what was underneath.",
    icon: "eraser",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      who,
      {
        id: "item",
        label: "What to remove",
        type: "text",
        required: true,
        placeholder: "e.g. sunglasses, scarf, watch, hat, bag, gloves, shoes",
      },
    ],
    mainPrompt:
      "Remove this accessory from {{who}}: {{item}}. Reconstruct the underlying area naturally (hair, skin, ears, hands, clothing) using surrounding information. Do not change face, identity, body, pose or background otherwise.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "socks-footwear",
    category: "clothing",
    clothingGroup: "extras",
    name: "Socks & Footwear",
    shortDescription: "Change, remove or add shoes and socks only.",
    icon: "personStanding",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      who,
      {
        id: "change",
        label: "What to do",
        type: "textarea",
        required: true,
        placeholder: "e.g. change trainers to brown boots, remove socks, add sandals, barefoot",
      },
    ],
    mainPrompt:
      "Edit only the socks and footwear on {{who}}: {{change}}. Do not alter unrelated parts of the photograph. Preserve identity, pose, clothing above the ankles unless the request needs a natural hem, and the background.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "outfit-builder",
    category: "clothing",
    clothingGroup: "builder",
    name: "Outfit Builder",
    shortDescription: "Assemble a look from top, bottom, shoes and extras.",
    icon: "layers",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      who,
      {
        id: "top",
        label: "Top",
        type: "text",
        placeholder: "e.g. T-shirt, shirt, jumper, jacket, coat",
        fallback: "a top that suits the chosen style",
      },
      {
        id: "bottom",
        label: "Bottom",
        type: "text",
        placeholder: "e.g. jeans, trousers, shorts, skirt",
        fallback: "bottoms that suit the chosen style",
      },
      {
        id: "footwear",
        label: "Footwear",
        type: "text",
        placeholder: "e.g. trainers, boots, shoes, sandals",
        fallback: "footwear that suits the chosen style",
      },
      {
        id: "accessories",
        label: "Accessories",
        type: "text",
        placeholder: "e.g. hat, sunglasses, watch, jewellery, bag",
        fallback: "no extra accessories",
      },
      {
        id: "style",
        label: "Style",
        type: "select",
        defaultValue: "casual",
        options: [
          { value: "casual", label: "Casual" },
          { value: "smart", label: "Smart" },
          { value: "formal", label: "Formal" },
          { value: "sports", label: "Sports" },
          { value: "beach", label: "Beach" },
          { value: "underwear or lingerie", label: "Underwear / lingerie" },
          { value: "work", label: "Work" },
          { value: "fancy dress", label: "Fancy dress" },
          { value: "historical", label: "Historical" },
          { value: "ridiculous novelty", label: "Ridiculous" },
          { value: "custom", label: "Custom" },
        ],
      },
    ],
    mainPrompt:
      "Dress {{who}} in a complete outfit. Top: {{top}}. Bottom: {{bottom}}. Footwear: {{footwear}}. Accessories: {{accessories}}. Overall style: {{style}}. Preserve face, identity, hairstyle, body proportions, pose, expression and skin tone. Do not change the background or other people.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "custom-clothing",
    category: "clothing",
    clothingGroup: "builder",
    name: "Custom Clothing Prompt",
    shortDescription: "“Dress this person in…” — only clothes change.",
    icon: "wand",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      who,
      {
        id: "description",
        label: "Dress this person in",
        type: "textarea",
        required: true,
        placeholder: "e.g. a rust waxed jacket, cream knit and muddy walking boots",
      },
    ],
    mainPrompt:
      "Dress {{who}} in {{description}}. Make only the requested clothing changes. Preserve face, identity, hairstyle, body proportions, pose, expression, skin tone and the background.",
    outputFormat: DEFAULT_OUTPUT,
  },
];
