import { DEFAULT_OUTPUT } from "./identity";
import type { EditGroupDefinition, ToolDefinition } from "./types";

export const EDIT_GROUPS: EditGroupDefinition[] = [
  {
    id: "basic",
    name: "Basic Editing",
    description: "Precise changes, crops and colour. Only what you ask for.",
  },
  {
    id: "recreate",
    name: "Expand & Recreate",
    description: "Wider frames, a new time of day, season, weather or camera angle.",
  },
  {
    id: "objects",
    name: "Object & Background Editing",
    description: "Remove, replace or isolate things in the frame.",
  },
  {
    id: "quality",
    name: "Quality & Colour",
    description: "Clarity, colour, glare and lens corrections.",
  },
  {
    id: "people",
    name: "People & Clothing",
    description: "Clothes and small people fixes. Faces stay themselves.",
  },
  {
    id: "faces",
    name: "People & Face Fixes",
    description: "Clarity, exposure and small face corrections. Identity stays.",
  },
  {
    id: "advanced",
    name: "Advanced Editing",
    description: "Lighting, product ads, angles and identity-safe edits.",
  },
];

const ASPECT_OPTIONS = [
  { value: "keep similar proportions", label: "Keep similar proportions" },
  { value: "1:1 square", label: "Square" },
  { value: "4:5 portrait", label: "4:5" },
  { value: "3:4 portrait", label: "3:4" },
  { value: "3:2 landscape", label: "3:2" },
  { value: "4:3 landscape", label: "4:3" },
  { value: "16:9 landscape", label: "16:9" },
  { value: "9:16 portrait", label: "9:16" },
];

export const EDITING_TOOLS: ToolDefinition[] = [
  // Existing tools — kept, grouped
  {
    id: "crop-straighten",
    category: "editing",
    editGroup: "basic",
    socialGroup: "social",
    name: "Crop & Straighten",
    shortDescription: "Level the horizon and tighten the frame.",
    icon: "crop",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "aspect",
        label: "Frame",
        type: "select",
        defaultValue: "keep",
        options: [
          { value: "keep", label: "Keep similar proportions" },
          { value: "square", label: "Square" },
          { value: "4:5", label: "Portrait 4:5" },
          { value: "16:9", label: "Landscape 16:9" },
        ],
      },
    ],
    mainPrompt:
      "Straighten the photograph so verticals and the horizon are level. Crop to a balanced composition with this frame: {{aspect}}. Do not change people, colours, clothing or the scene. Do not add or remove objects. No tilt-shift effect.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "reframe",
    category: "editing",
    editGroup: "basic",
    name: "Reframe",
    shortDescription: "Recompose the shot without changing the subject.",
    icon: "frame",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "framing",
        label: "New framing",
        type: "select",
        defaultValue: "tighter portrait",
        options: [
          { value: "tighter portrait", label: "Tighter portrait" },
          { value: "head and shoulders", label: "Head and shoulders" },
          { value: "environmental wide", label: "More environment" },
          { value: "rule of thirds", label: "Rule of thirds" },
        ],
      },
    ],
    mainPrompt:
      "Reframe this photograph: {{framing}}. Keep the same subject, identity, clothing and setting. You may extend the background slightly if needed for the new crop, matching the original lighting and textures. Do not invent new people or objects of interest.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "colour-correction",
    category: "editing",
    editGroup: "quality",
    name: "Colour Correction",
    shortDescription: "Fix white balance, exposure and colour cast.",
    icon: "sliders",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "look",
        label: "Aim",
        type: "select",
        defaultValue: "natural",
        options: [
          { value: "natural", label: "Natural and true to life" },
          { value: "warmer", label: "A little warmer" },
          { value: "cooler", label: "A little cooler" },
          { value: "punchy", label: "Slightly more punch" },
        ],
      },
    ],
    mainPrompt:
      "Correct the colour and exposure of this photograph. Aim: {{look}}. Fix white balance, colour cast, underexposure or overexposure. Do not restyle, crop, change the sky, or retouch faces. Do not apply a beauty filter.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "remove-background",
    category: "editing",
    editGroup: "objects",
    name: "Remove Background",
    shortDescription: "Cut the subject out onto a clean backdrop.",
    icon: "imageOff",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "backdrop",
        label: "Backdrop",
        type: "select",
        defaultValue: "plain off-white",
        options: [
          { value: "plain off-white", label: "Off-white" },
          { value: "plain warm grey", label: "Warm grey" },
          { value: "plain black", label: "Black" },
          { value: "transparent-looking white studio sweep", label: "Studio sweep" },
        ],
      },
    ],
    mainPrompt:
      "Remove the original background and place the unaltered subject on a {{backdrop}} backdrop. Keep hair, edges, clothing and shadows natural. Do not change the subject. No extra props.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "background-blur",
    category: "editing",
    editGroup: "quality",
    name: "Background Blur",
    shortDescription: "Soften the background, keep the subject sharp.",
    icon: "aperture",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "amount",
        label: "Blur",
        type: "select",
        defaultValue: "gentle portrait depth of field",
        options: [
          { value: "gentle portrait depth of field", label: "Gentle" },
          { value: "strong telephoto bokeh", label: "Strong" },
        ],
      },
    ],
    mainPrompt:
      "Keep the subject perfectly sharp and apply {{amount}} to the background only. Do not change faces, clothing, colours or composition. The blur should look like a camera aperture, not a smudge.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "object-removal",
    category: "editing",
    editGroup: "objects",
    toolkitGroup: "erase",
    name: "Replace or Remove an Object",
    shortDescription: "Take an object out, or swap it for something else.",
    icon: "eraser",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "action",
        label: "Action",
        type: "select",
        defaultValue: "removing",
        options: [
          { value: "removing", label: "Remove" },
          { value: "replacing", label: "Replace" },
        ],
      },
      {
        id: "target",
        label: "Object and location",
        type: "textarea",
        required: true,
        placeholder: "e.g. the bin on the left, the tourist in the red coat",
      },
      {
        id: "replacement",
        label: "Replace with",
        type: "text",
        placeholder: "e.g. a terracotta pot of herbs",
        fallback: "a natural continuation of the surrounding area",
        help: "Only needed when replacing.",
      },
    ],
    mainPrompt:
      "Edit the attached image by {{action}} this specific object: {{target}}. If replacing it, replace it with {{replacement}}. Make the edit blend naturally with the surrounding area, matching the original lighting, shadows, perspective, scale, colours, textures and visual style. Keep all other subjects, objects, text, background elements, facial features, composition and important details exactly as they are. Do not add, remove, reposition or redesign anything else. The final image should look like the original image with only the requested object edited.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "custom-edit",
    category: "editing",
    editGroup: "advanced",
    name: "Advanced Custom Edit",
    shortDescription: "Describe a precise change in your own words.",
    icon: "wand",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "instruction",
        label: "What should change",
        type: "textarea",
        required: true,
        placeholder: "e.g. replace the sky with a calm evening sky, keep everything else",
      },
      {
        id: "preserve",
        label: "Preserve original",
        type: "select",
        defaultValue:
          "Preserve the original subject, identity, pose, composition, background, lighting, colours and important details. Make only the requested change.",
        options: [
          {
            value:
              "Preserve the original subject, identity, pose, composition, background, lighting, colours and important details. Make only the requested change.",
            label: "On — only the requested change",
          },
          {
            value:
              "A creative transformation is allowed where the instruction requires it. Keep the person recognisable unless asked otherwise.",
            label: "Off — allow a creative change",
          },
        ],
      },
    ],
    mainPrompt:
      "Apply only this requested change: {{instruction}}. Do not redesign the photograph. Do not beautify faces. Do not change anything that was not asked for. {{preserve}}",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Basic Editing ——
  {
    id: "preserve-original-edit",
    category: "editing",
    editGroup: "basic",
    name: "Preserve the Original",
    shortDescription: "Make one requested change. Leave everything else.",
    icon: "focus",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "edit",
        label: "The one change",
        type: "textarea",
        required: true,
        placeholder: "e.g. remove the lamp-post behind the left shoulder",
      },
    ],
    mainPrompt:
      "Edit the attached image while preserving everything that does not need to change. Make only this specific edit: {{edit}}. Keep the original subject, facial features, pose, proportions, composition, perspective, background, lighting, colors, textures, and important details unchanged unless I explicitly ask you to modify them. Do not redesign, reinterpret, replace, or add elements unnecessarily. Maintain the original visual style and overall appearance. The final image should look like the original image with only the requested edit applied.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "precise-final-edits",
    category: "editing",
    editGroup: "basic",
    name: "Precise Final Edits",
    shortDescription: "Apply a short list of changes, nothing more.",
    icon: "sliders",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "edits",
        label: "Requested changes",
        type: "textarea",
        required: true,
        placeholder: "e.g. 1) brighten the window  2) tidy the collar  3) keep everything else",
      },
    ],
    mainPrompt:
      "Apply the following specific edits to the attached image: {{edits}}. Make only these changes and preserve everything else exactly as it appears in the original image. Keep all unmentioned subjects, facial features, objects, text, colors, proportions, positions, background elements, lighting, textures, perspective, composition, and visual style unchanged. Ensure each edit blends naturally with the original image and does not unintentionally affect surrounding details. Do not add, remove, redesign, reposition, or reinterpret anything unless explicitly requested. The final image should look like the original with only the specified edits applied.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "change-aspect-ratio",
    category: "editing",
    editGroup: "recreate",
    socialGroup: "custom",
    name: "Change Aspect Ratio",
    shortDescription: "Reformat the frame. Extend or crop naturally.",
    icon: "ratio",
    identityPreservation: "strict",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "aspect",
        label: "Aspect ratio",
        type: "select",
        defaultValue: "4:5 portrait",
        options: ASPECT_OPTIONS,
      },
    ],
    mainPrompt:
      "Reformat this image into {{aspect}} while preserving the original subject and important details. Extend or crop the image naturally where necessary. Keep the composition, perspective, lighting and visual style consistent. Do not unnecessarily alter the subject or invent unrelated details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "expand-photo",
    category: "editing",
    editGroup: "recreate",
    socialGroup: "custom",
    name: "Expand the Photo",
    shortDescription: "Continue the scene beyond the original borders.",
    icon: "expand",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "size",
        label: "Expand to",
        type: "select",
        defaultValue: "16:9 landscape",
        options: [
          ...ASPECT_OPTIONS.filter((o) => o.value !== "keep similar proportions"),
          { value: "custom", label: "Custom" },
        ],
      },
      {
        id: "customSize",
        label: "Custom size",
        type: "text",
        placeholder: "e.g. 2:1 panoramic",
        fallback: "the selected aspect ratio",
        help: "Only needed if you chose Custom.",
      },
    ],
    mainPrompt:
      "Expand this image beyond its current borders to {{size}} while keeping everything inside the original image unchanged. If Custom is selected, expand to {{customSize}}. Naturally continue the existing background, environment, floor, walls, sky, scenery, objects, lighting, textures, patterns, depth, and perspective into the new space. Make the expansion seamless so it looks like the wider image was captured that way originally.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "time-of-day",
    category: "editing",
    editGroup: "recreate",
    name: "Recreate a Different Time of Day",
    shortDescription: "Sunrise, golden hour, sunset or night. Same scene.",
    icon: "sun",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "current",
        label: "Current time of day",
        type: "select",
        defaultValue: "as it appears",
        options: [
          { value: "as it appears", label: "As it appears" },
          { value: "sunrise", label: "Sunrise" },
          { value: "midday", label: "Midday" },
          { value: "golden hour", label: "Golden hour" },
          { value: "sunset", label: "Sunset" },
          { value: "night", label: "Night" },
        ],
      },
      {
        id: "target",
        label: "Change to",
        type: "select",
        defaultValue: "golden hour",
        options: [
          { value: "sunrise", label: "Sunrise" },
          { value: "golden hour", label: "Golden hour" },
          { value: "sunset", label: "Sunset" },
          { value: "night", label: "Night" },
        ],
      },
    ],
    mainPrompt:
      "Change this scene from {{current}} to {{target}}. Adjust the sky, light direction, colour temperature, reflections, shadows, windows, and surrounding environment so the entire scene convincingly matches the new time of day. Keep people, buildings and important objects in place. Do not invent a different location.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Object & background ——
  {
    id: "remove-photobombers",
    category: "editing",
    editGroup: "objects",
    name: "Remove Unwanted People",
    shortDescription: "Clear photobombers and rebuild the background.",
    icon: "userX",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "who",
        label: "Who to remove, and where",
        type: "textarea",
        required: true,
        placeholder: "e.g. the person in the blue coat on the far right",
      },
    ],
    mainPrompt:
      "Remove the unwanted person or people from the attached image: {{who}}. Reconstruct the background naturally using the surrounding environment, lighting, shadows, textures and perspective. Keep all other people, faces, objects and composition unchanged. Do not alter the identity, pose or appearance of anyone who remains.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "change-background",
    category: "editing",
    editGroup: "objects",
    toolkitGroup: "scene",
    name: "Change the Background",
    shortDescription: "New setting. Same person, same pose.",
    icon: "layers",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "background",
        label: "New background",
        type: "textarea",
        required: true,
        placeholder: "e.g. a quiet bookshop, late afternoon window light",
      },
    ],
    mainPrompt:
      "Edit the attached image by changing only the background to {{background}}. Keep the main subject exactly as it appears in the original image, including its shape, facial features, pose, proportions, clothing, colors, textures, and important details. Make the new background blend naturally with the subject by matching the perspective, lighting, shadows, depth, and overall visual style. Do not alter, reposition, redesign, or replace the main subject or any elements I have not asked you to change. The final image should look natural and consistent, with only the requested background changed.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "remove-text-watermark",
    category: "editing",
    editGroup: "objects",
    name: "Remove Text or Watermarks",
    shortDescription: "Clean marks from a photograph or design you own.",
    icon: "type",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Use this tool only for images and designs you own or have permission to edit.",
    fields: [
      {
        id: "mark",
        label: "What to remove",
        type: "text",
        required: true,
        placeholder: "e.g. the date stamp in the corner, the logo on the mug",
      },
    ],
    mainPrompt:
      "Remove the highlighted {{mark}} from this image and reconstruct the area underneath using the surrounding colours, textures, patterns, lighting, and perspective. Make the result look clean and seamless without affecting nearby elements. Do not change faces, clothing or the rest of the scene.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "edit-text-in-image",
    category: "editing",
    editGroup: "objects",
    name: "Edit Text in an Image",
    shortDescription: "Replace lettering. Keep the rest of the design.",
    icon: "type",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Use this tool only for images and designs you own or have permission to edit.",
    fields: [
      {
        id: "existing",
        label: "Existing text",
        type: "text",
        required: true,
        placeholder: "e.g. OPEN SUNDAY",
      },
      {
        id: "replacement",
        label: "New text",
        type: "text",
        required: true,
        placeholder: "e.g. CLOSED MONDAY",
      },
    ],
    mainPrompt:
      "Edit only the text in the attached image. Replace {{existing}} with {{replacement}}. Keep the original font style, size, weight, color, alignment, spacing, positioning, and overall typography as closely as possible. Preserve the existing layout, graphics, background, images, colors, and all other design elements exactly as they are. Make sure the new text is spelled correctly, clearly readable, and fits naturally within the original space. Do not redesign the image or modify anything other than the specified text.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Quality & colour ——
  {
    id: "remove-glare",
    category: "editing",
    editGroup: "quality",
    name: "Remove Glare / Reflections",
    shortDescription: "Reduce hotspots and glass reflections.",
    icon: "sun",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "area",
        label: "Affected area",
        type: "text",
        required: true,
        placeholder: "e.g. glasses lenses, the shop window, the forehead",
      },
    ],
    mainPrompt:
      "Reduce or remove the unwanted glare and reflections from {{area}} while preserving the original subject, facial features, objects, colours, textures and lighting. Reconstruct obscured details naturally where possible. Keep the result realistic and avoid inventing unsupported details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "fix-red-eye",
    category: "editing",
    editGroup: "faces",
    name: "Fix Red-Eye",
    shortDescription: "Correct flash red-eye, keep the real eye colour.",
    icon: "eye",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Correct the red-eye effect in the attached photograph while preserving the person’s natural eye colour, eye shape, expression and identity. Keep the correction subtle and realistic. Do not alter any other facial features or image details.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "lens-correction",
    category: "editing",
    editGroup: "quality",
    name: "Lens Correction & Straighten",
    shortDescription: "Fix distortion, tilt and leaning verticals.",
    icon: "rotate",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Correct the perspective, lens distortion and uneven alignment in this photograph. Straighten vertical and horizontal lines where appropriate while preserving the original subject, proportions, composition, lighting and important details. Keep the result natural and photorealistic.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— People & clothing ——
  {
    id: "change-clothing",
    category: "editing",
    editGroup: "people",
    name: "Change Colours or Clothing",
    shortDescription: "Recolour or restyle one item. Keep the person.",
    icon: "shirt",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "target",
        label: "What to change",
        type: "text",
        required: true,
        placeholder: "e.g. the blue jumper, the wall behind her",
      },
      {
        id: "change",
        label: "Change it to",
        type: "text",
        required: true,
        placeholder: "e.g. a rust-red knit, a sage green",
      },
    ],
    mainPrompt:
      "Edit the attached image by changing only {{target}} to {{change}}. Preserve the subject’s identity, facial features, pose, body proportions, hairstyle, expression, and all other details exactly as they appear in the original image. Make the change look natural by maintaining the original lighting, shadows, textures, folds, perspective, and visual style. Do not alter the background, composition, or any elements I have not specifically asked you to change. The final image should look like the original with only the requested color or clothing change applied.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "fix-closed-eyes",
    category: "editing",
    editGroup: "people",
    name: "Fix Closed Eyes",
    shortDescription: "Open closed or half-closed eyes naturally.",
    icon: "scanEye",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Correct the person’s closed or half-closed eyes so they look naturally open and consistent with their face, expression, gaze direction, lighting, and eye shape. Keep the edit subtle and realistic, without changing the person’s identity or overall expression.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "fix-wrinkled-clothing",
    category: "editing",
    editGroup: "people",
    name: "Fix Wrinkled Clothing",
    shortDescription: "Neaten creases without painting the fabric away.",
    icon: "shirt",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Smooth out distracting wrinkles, creases, bunching, and uneven fabric in the clothing while keeping the material, fit, seams, texture, and natural folds realistic. Make the outfit look neat and well-presented without making it appear digitally painted. Do not change the person, pose or background.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Advanced ——
  {
    id: "product-ad-edit",
    category: "editing",
    editGroup: "advanced",
    name: "Product Ad Edit",
    shortDescription: "Turn a product shot into premium advertisement.",
    icon: "shoppingBag",
    identityPreservation: "creative",
    version: 1,
    active: true,
    example:
      "Turn this smartwatch photo into a premium advertisement. Keep the shape, colour, logo, and screen unchanged. Add a clean black studio background with soft spotlighting.",
    fields: [
      {
        id: "product",
        label: "Product",
        type: "text",
        placeholder: "e.g. the smartwatch, the bottle",
        fallback: "the product in the photograph",
      },
      {
        id: "background",
        label: "Background style",
        type: "text",
        placeholder: "e.g. clean black studio, marble table",
        fallback: "a clean premium studio background",
      },
      {
        id: "lighting",
        label: "Lighting style",
        type: "text",
        placeholder: "e.g. soft spotlighting, rim light",
        fallback: "soft premium studio lighting",
      },
    ],
    mainPrompt:
      "Turn this product image into a premium advertisement for {{product}}. Keep its shape, color, logo, and key details unchanged. Add {{background}}, {{lighting}}, and premium studio quality.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "dramatic-lighting",
    category: "editing",
    editGroup: "advanced",
    toolkitGroup: "sky",
    name: "Dramatic Lighting",
    shortDescription: "Upgrade the light. Keep the photograph the same.",
    icon: "lamp",
    identityPreservation: "strict",
    version: 1,
    active: true,
    example:
      "Keep the image the same but add dramatic Rembrandt lighting with realistic shadows and subtle highlights.",
    fields: [
      {
        id: "style",
        label: "Lighting style",
        type: "text",
        placeholder: "e.g. Rembrandt, golden hour, soft window",
        fallback: "dramatic cinematic lighting",
      },
      {
        id: "direction",
        label: "Light direction",
        type: "select",
        defaultValue: "as suggested by the photograph",
        options: [
          { value: "as suggested by the photograph", label: "Keep similar" },
          { value: "from camera-left", label: "From the left" },
          { value: "from camera-right", label: "From the right" },
          { value: "from above", label: "From above" },
          { value: "from behind as rim light", label: "From behind" },
          { value: "on-camera soft fill", label: "Front fill" },
        ],
      },
      {
        id: "mood",
        label: "Intensity",
        type: "select",
        defaultValue: "a natural photographic intensity",
        options: [
          { value: "a natural photographic intensity", label: "Natural" },
          { value: "soft and gentle", label: "Soft" },
          { value: "strong and dramatic", label: "Strong" },
        ],
      },
    ],
    mainPrompt:
      "Keep the image the same but completely upgrade the lighting. Add {{style}}, light direction {{direction}}, intensity {{mood}}, realistic shadows, subtle highlights, and depth while preserving the subject's identity and the original composition.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "face-identity-protect",
    category: "editing",
    editGroup: "advanced",
    name: "Face & Identity Protection",
    shortDescription: "Lock the face. Change only what you name.",
    icon: "scanFace",
    identityPreservation: "strict",
    version: 1,
    active: true,
    example:
      "Keep my face exactly the same as the original image. Only change the background and improve the lighting.",
    fields: [
      {
        id: "edit",
        label: "Only edit this",
        type: "textarea",
        required: true,
        placeholder: "e.g. the background and the lighting",
      },
    ],
    mainPrompt:
      "Keep my face exactly the same as the original image. Do not change my eyes, nose, mouth, skin tone, hairstyle, or facial expression. Only edit {{edit}}.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "camera-angle",
    category: "editing",
    editGroup: "recreate",
    name: "Camera Angle Recreation",
    shortDescription: "The same scene from a new viewpoint.",
    icon: "move3d",
    identityPreservation: "creative",
    version: 1,
    active: true,
    example:
      "Recreate this image from a low-angle hero shot. Keep my pose and outfit the same while adjusting the lighting and perspective naturally.",
    fields: [
      {
        id: "angle",
        label: "New camera angle",
        type: "text",
        required: true,
        placeholder: "e.g. low-angle hero shot, three-quarter over the shoulder",
      },
    ],
    mainPrompt:
      "Recreate this image from a {{angle}}. Keep the subject, pose, clothing, and key details consistent. Adjust lighting, shadows, and perspective so the new angle looks realistic.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "natural-face-enhance",
    category: "editing",
    editGroup: "faces",
    name: "Natural Face Enhancement",
    shortDescription: "Clearer, better-exposed face. Same person.",
    icon: "scanFace",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Improve facial clarity and exposure in this photograph while keeping the person’s identity completely unchanged. Recover natural skin texture, even light on the face, and fine detail. Do not reshape, beautify, smooth into plastic skin, or invent features.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "face-exposure",
    category: "editing",
    editGroup: "faces",
    name: "Face Exposure",
    shortDescription: "A face that is too dark, too bright, or uneven.",
    icon: "sun",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "problem",
        label: "What’s wrong",
        type: "select",
        defaultValue: "the face is too dark",
        options: [
          { value: "the face is too dark", label: "Too dark" },
          { value: "the face is too bright", label: "Too bright" },
          { value: "the face is unevenly lit", label: "Uneven" },
        ],
      },
    ],
    mainPrompt:
      "Correct facial exposure: {{problem}}. Balance light on the face so it looks naturally photographed. Preserve identity, facial structure, skin tone, expression and everything else in the frame.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "eye-enhancement",
    category: "editing",
    editGroup: "faces",
    name: "Eye Enhancement",
    shortDescription: "Subtle clarity and catchlights. Same eyes.",
    icon: "eye",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Improve eye clarity and catchlights subtly. Do not change eye shape, colour, gaze, identity or expression. Keep the result photographic, not glamorous retouching.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "hair-flyaway",
    category: "editing",
    editGroup: "faces",
    name: "Hair & Flyaway Cleanup",
    shortDescription: "Tidy stray hairs. Keep the hairstyle.",
    icon: "wand",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Remove distracting stray hairs and flyaways while preserving the hairstyle, natural texture, colour and volume. Do not change the face, identity, clothing or background.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "teeth-cleanup",
    category: "editing",
    editGroup: "faces",
    name: "Natural Teeth Cleanup",
    shortDescription: "A little less stain. Still real teeth.",
    icon: "smile",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Subtly improve distracting tooth discolouration while retaining realistic tooth shape, spacing and appearance. Do not whiten to an artificial glare. Do not change lips, face, identity or expression.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "harsh-flash-fix",
    category: "editing",
    editGroup: "faces",
    name: "Harsh Flash Fix",
    shortDescription: "Calm a blown flash on the face.",
    icon: "lamp",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Reduce harsh on-camera flash on the face: shine, hot spots and uneven exposure. Balance facial light so it looks natural. Preserve identity, facial structure, skin texture, clothing and background. Do not beautify.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "face-balance",
    category: "editing",
    editGroup: "faces",
    name: "Face Balance",
    shortDescription: "Even light and clarity when more than one face is in the shot.",
    icon: "images",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Where multiple people appear, balance facial exposure and clarity so everyone is naturally visible. Preserve each person’s identity, facial structure, expression, skin tone and age. Do not beautify, swap faces, or change clothing or the scene.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "hair-colour",
    category: "editing",
    editGroup: "faces",
    name: "Hair Colour",
    shortDescription: "Change hair colour. Same cut, same person.",
    icon: "palette",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "who",
        label: "Which person",
        type: "text",
        placeholder: "e.g. the person on the left",
        fallback: "the main person",
      },
      {
        id: "colour",
        label: "New hair colour",
        type: "text",
        required: true,
        placeholder: "e.g. natural dark brown, silver, warm auburn",
      },
    ],
    mainPrompt:
      "Change only the hair colour of {{who}} to {{colour}}. Preserve face, identity, hairstyle shape, length, texture, expression and the rest of the photograph. Do not restyle the cut or change clothing.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "glasses-on-off",
    category: "editing",
    editGroup: "faces",
    name: "Glasses On / Off",
    shortDescription: "Add or remove glasses. The eyes stay theirs.",
    icon: "eye",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "action",
        label: "Action",
        type: "select",
        defaultValue: "remove the glasses",
        options: [
          { value: "remove the glasses", label: "Remove glasses" },
          { value: "add glasses", label: "Add glasses" },
        ],
      },
      {
        id: "style",
        label: "Frame style if adding",
        type: "text",
        placeholder: "e.g. thin metal, tortoiseshell",
        fallback: "simple everyday frames that suit the face",
      },
    ],
    mainPrompt:
      "{{action}} on the main person. If adding, use {{style}}. Reconstruct the eyes or the bridge of the nose naturally from the photograph. Preserve identity, eye shape, expression and everything else. No beautification.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "season-change",
    category: "editing",
    editGroup: "recreate",
    name: "Season Change",
    shortDescription: "The same place, a different season.",
    icon: "sun",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "season",
        label: "Season",
        type: "select",
        defaultValue: "autumn",
        options: [
          { value: "spring", label: "Spring" },
          { value: "summer", label: "Summer" },
          { value: "autumn", label: "Autumn" },
          { value: "winter", label: "Winter" },
        ],
      },
    ],
    mainPrompt:
      "Change this scene to {{season}} while keeping the same place, buildings, people and identity. Adjust trees, ground, light and sky so the season is convincing. Do not invent a different location or different people.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "realistic-weather",
    category: "editing",
    editGroup: "recreate",
    name: "Realistic Rain or Snow",
    shortDescription: "Weather on this scene. Same place, same people.",
    icon: "cloud",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "weather",
        label: "Weather",
        type: "select",
        defaultValue: "light falling snow",
        options: [
          { value: "light rain", label: "Light rain" },
          { value: "heavy rain", label: "Heavy rain" },
          { value: "light falling snow", label: "Falling snow" },
          { value: "frost and a dusting of snow", label: "Frost" },
          { value: "soft mist", label: "Mist" },
        ],
      },
    ],
    mainPrompt:
      "Add realistic {{weather}} to this existing scene. Keep the same place, buildings, people and identity. Match perspective, wet surfaces, lighting and depth. Do not invent a different location.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "sensor-spots",
    category: "editing",
    editGroup: "quality",
    name: "Sensor Spots & Dust",
    shortDescription: "Specks in the sky or even tones. Scene stays.",
    icon: "eraser",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Remove dust spots, sensor specks and small blobs especially in the sky and even-toned areas. Reconstruct those tiny patches from neighbouring pixels. Do not change the scene, people, colours or composition.",
    outputFormat: DEFAULT_OUTPUT,
  },
];
