import { DEFAULT_OUTPUT } from "./identity";
import type { FunGroupDefinition, ToolDefinition } from "./types";

export const FUN_GROUPS: FunGroupDefinition[] = [
  {
    id: "toys",
    name: "Toys & Collectibles",
    description: "Action figures, minis and toy packaging.",
  },
  {
    id: "funny",
    name: "Funny & Cartoon",
    description: "Caricatures, cartoons and deadpan portraits.",
  },
  {
    id: "weird",
    name: "Weird & Wonderful",
    description: "Surreal scale, creatures and impossible scenes.",
  },
  {
    id: "movie",
    name: "Movie & Poster Maker",
    description: "Fictional posters and cinematic casting.",
  },
  {
    id: "retro",
    name: "Retro & Nostalgia",
    description: "Film, flash and camcorder memories.",
  },
  {
    id: "collages",
    name: "Collages & Memories",
    description: "Scrapbooks, Polaroids, strips and boards.",
  },
  {
    id: "worlds",
    name: "Worlds & Adventures",
    description: "Deliberate creative worlds. Not for repair.",
  },
];

const TOY_OUTPUT =
  "Return a single product photograph of the collectible. Packaging text should be readable. No watermarks.";

const POSTER_OUTPUT =
  "Return a single promotional poster. Title and tagline typography must be spelled exactly as given and stay readable. No watermarks.";

export const FUN_TOOLS: ToolDefinition[] = [
  // Existing starter tools — kept, grouped
  {
    id: "funny-expression",
    category: "fun",
    funGroup: "funny",
    name: "Funny Expression",
    shortDescription: "A comic, over-the-top version of the same face.",
    icon: "smile",
    identityPreservation: "creative",
    version: 1,
    active: true,
    example: "A perfectly ordinary portrait turned into a cartoonish gasp.",
    mainPrompt:
      "Transform this photograph into a humorous version of the same moment. Slightly exaggerate facial expression and body language for a comic effect, as if a candid out-take. Keep the same person, clothing and setting. Do not turn it into a cartoon, illustration or caricature drawing — it must remain a photograph.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "fancy-dress",
    category: "fun",
    funGroup: "funny",
    clothingGroup: "play",
    name: "Fancy Dress",
    shortDescription: "Dress the subject in a costume you choose.",
    icon: "shirt",
    identityPreservation: "creative",
    version: 1,
    active: true,
    example: "The same person in a Victorian explorer outfit.",
    note: "Also in Clothing Studio. Built once — not a second costume tool.",
    fields: [
      {
        id: "preset",
        label: "Costume",
        type: "select",
        defaultValue: "a custom costume described below",
        options: [
          { value: "a custom costume described below", label: "Custom — I'll describe it" },
          { value: "a chicken costume", label: "Chicken" },
          { value: "a dinosaur costume", label: "Dinosaur" },
          { value: "a superhero costume", label: "Superhero" },
          { value: "an astronaut costume", label: "Astronaut" },
          { value: "a pirate costume", label: "Pirate" },
          { value: "a cowboy outfit", label: "Cowboy" },
          { value: "a medieval knight costume", label: "Medieval knight" },
          { value: "a Roman costume", label: "Roman" },
          { value: "Victorian clothing", label: "Victorian" },
          { value: "a chef's whites", label: "Chef" },
          { value: "a firefighter costume", label: "Firefighter" },
          { value: "a fictional police-style costume", label: "Police-style (fictional)" },
          { value: "a Santa costume", label: "Santa" },
          { value: "a clown costume", label: "Clown" },
          { value: "an inflatable costume", label: "Inflatable" },
          { value: "a mascot costume", label: "Mascot" },
          { value: "an animal costume", label: "Animal costume" },
          { value: "ridiculous novelty fancy dress", label: "Ridiculous novelty" },
        ],
      },
      {
        id: "costume",
        label: "Describe the costume",
        type: "text",
        placeholder: "e.g. 1970s disco, gardener in wellies, a blue T-rex onesie",
        fallback: "the selected costume",
        help: "Required if you chose Custom. Extra detail is always welcome.",
      },
    ],
    mainPrompt:
      "Keep the same person and face. Change only their clothing and immediate accessories to this costume: {{preset}}. Extra detail: {{costume}}. Match lighting and photographic quality to the original. The result must still look like a real photograph of the same person.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "decade-trip",
    category: "fun",
    funGroup: "retro",
    name: "Decade Trip",
    shortDescription: "Send the photograph back to another era.",
    icon: "clock",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "decade",
        label: "Decade",
        type: "select",
        required: true,
        defaultValue: "1950s",
        options: [
          { value: "1920s", label: "1920s" },
          { value: "1940s", label: "1940s" },
          { value: "1950s", label: "1950s" },
          { value: "1960s", label: "1960s" },
          { value: "1970s", label: "1970s" },
          { value: "1980s", label: "1980s" },
          { value: "1990s", label: "1990s" },
        ],
      },
    ],
    mainPrompt:
      "Restage this photograph as if it were taken in the {{decade}}. Keep the same people recognisable. Adjust clothing, hair, props and photographic process to that decade. The result should look like an authentic photograph from the period, not a costume-party snapshot.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "action-poster",
    category: "fun",
    funGroup: "movie",
    name: "Action Poster",
    shortDescription: "Turn the photo into a tongue-in-cheek movie poster.",
    icon: "clapperboard",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "title",
        label: "Film title",
        type: "text",
        required: true,
        placeholder: "e.g. The Last Biscuit",
      },
      {
        id: "genre",
        label: "Genre",
        type: "select",
        defaultValue: "spy thriller",
        options: [
          { value: "spy thriller", label: "Spy thriller" },
          { value: "rom-com", label: "Rom-com" },
          { value: "disaster movie", label: "Disaster movie" },
          { value: "western", label: "Western" },
          { value: "space opera", label: "Space opera" },
        ],
      },
    ],
    mainPrompt:
      "Create a humorous theatrical movie poster using this photograph as the hero image. Genre: {{genre}}. Title: {{title}}. Keep the same person recognisable as the star. Add dramatic poster lighting and tasteful title typography. Do not add extra people.",
    outputFormat:
      "Return a single portrait-oriented poster image. Title typography should be readable. No watermarks.",
  },
  {
    id: "tiny-world",
    category: "fun",
    funGroup: "toys",
    name: "Tiny World",
    shortDescription: "Shrink the subject into a miniature scene.",
    icon: "personStanding",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "scene",
        label: "Giant world",
        type: "text",
        placeholder: "e.g. on a biscuit, in a teacup, on a bookshelf",
        defaultValue: "standing on a kitchen table among giant props",
      },
    ],
    mainPrompt:
      "Photograph the same recognisable person as a tiny figure in this miniature world: {{scene}}. Keep facial identity. Use realistic scale, shadows and depth of field as if shot with a macro lens. Still a photograph, not an illustration.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Toys & Collectibles ——
  {
    id: "action-figure-box",
    category: "fun",
    funGroup: "toys",
    name: "Action Figure in a Box",
    shortDescription: "A collectible figure in realistic retail packaging.",
    icon: "package",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "name",
        label: "Character name",
        type: "text",
        placeholder: "e.g. Captain Moreton",
        fallback: "a fitting character name",
      },
      {
        id: "outfit",
        label: "Outfit",
        type: "text",
        placeholder: "e.g. explorer kit, space suit",
        fallback: "an outfit that suits the person",
      },
      {
        id: "accessories",
        label: "Accessories",
        type: "text",
        placeholder: "e.g. camera, mug, garden trowel",
        fallback: "a few personal accessories",
      },
      {
        id: "theme",
        label: "Theme",
        type: "text",
        placeholder: "e.g. garden hero, weekend spy",
        fallback: "a theme that suits the photograph",
      },
      {
        id: "packaging",
        label: "Packaging style",
        type: "select",
        defaultValue: "premium blister card with a clear window",
        options: [
          { value: "premium blister card with a clear window", label: "Blister card" },
          { value: "collector window box", label: "Window box" },
          { value: "deluxe two-pack carton", label: "Deluxe carton" },
        ],
      },
      {
        id: "description",
        label: "Character description",
        type: "textarea",
        placeholder: "Optional extra detail for the backing card",
        fallback: "a short heroic blurb",
      },
    ],
    mainPrompt:
      "Transform the person in this photo into a highly detailed collectible action figure displayed inside realistic retail packaging. Preserve their recognisable identity, hairstyle and key appearance. Include {{accessories}}, {{outfit}} and {{theme}}. Character name: {{name}}. Character description: {{description}}. Packaging style: {{packaging}}. Add a transparent plastic window, printed backing card, product photography lighting and realistic miniature scale. Make it look like a premium collectible toy.",
    outputFormat: TOY_OUTPUT,
  },
  {
    id: "chibi-version",
    category: "fun",
    funGroup: "toys",
    name: "Chibi Version",
    shortDescription: "A cute oversized-head collectible figure.",
    icon: "gift",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform the subject into a cute 3D Chibi-style character with an oversized head, expressive eyes and a small stylised body. Preserve recognisable features, hairstyle and important clothing details. Use smooth toy-like textures, soft lighting and a polished collectible-figure appearance.",
    outputFormat:
      "Return a single toy-figure photograph or product render on a simple surface. No watermarks.",
  },
  {
    id: "miniature-me",
    category: "fun",
    funGroup: "toys",
    name: "Miniature Me",
    shortDescription: "A tiny realistic version of the same person.",
    icon: "puzzle",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "location",
        label: "Location",
        type: "text",
        placeholder: "e.g. on a bookshelf, beside a teacup",
        fallback: "a convincing miniature setting",
      },
    ],
    mainPrompt:
      "Turn the person in this image into a tiny realistic miniature version of themselves, standing or sitting in {{location}}. Preserve their recognisable identity, clothing and pose. Make the scale difference convincing, with realistic shadows, perspective and photographic detail.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "toy-packaging",
    category: "fun",
    funGroup: "toys",
    name: "Toy Packaging Designer",
    shortDescription: "Design the retail box around the subject.",
    icon: "box",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "name",
        label: "Character name",
        type: "text",
        placeholder: "e.g. Super Steve",
        fallback: "a fitting character name",
      },
      {
        id: "theme",
        label: "Occupation or theme",
        type: "text",
        placeholder: "e.g. botanist, DJ, time traveller",
        fallback: "a theme that suits the subject",
      },
      {
        id: "outfit",
        label: "Outfit",
        type: "text",
        placeholder: "e.g. field jacket and boots",
        fallback: "an outfit that suits the theme",
      },
      {
        id: "accessories",
        label: "Accessories",
        type: "text",
        placeholder: "e.g. radio, map, flask",
        fallback: "a few matching accessories",
      },
      {
        id: "style",
        label: "Packaging style",
        type: "select",
        defaultValue: "premium collector window box",
        options: [
          { value: "premium collector window box", label: "Collector window box" },
          { value: "classic blister card", label: "Blister card" },
          { value: "retro cereal-style carton", label: "Retro carton" },
        ],
      },
    ],
    mainPrompt:
      "Create a premium collectible toy package based on the person or subject in this image. Preserve the recognisable appearance of the subject. Include the character name {{name}}, occupation or theme {{theme}}, outfit {{outfit}}, accessories {{accessories}} and packaging style {{style}}. Use realistic retail packaging, a transparent display window, printed graphics, product photography lighting and believable miniature scale.",
    outputFormat: TOY_OUTPUT,
  },
  {
    id: "building-block-version",
    category: "fun",
    funGroup: "toys",
    name: "Building-Block Version",
    shortDescription: "Recreate the scene in plastic bricks.",
    icon: "blocks",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Recreate the subject as a detailed building-block character and scene. Preserve the recognisable clothing, pose and key features while translating the image into realistic plastic bricks, miniature accessories and a photographed model-display setting.",
    outputFormat:
      "Return a single photographed brick-model display. No brand logos. No watermarks.",
  },

  // —— Funny & Cartoon ——
  {
    id: "roast-caricature",
    category: "fun",
    funGroup: "funny",
    name: "Roast Me Caricature",
    shortDescription: "A playful, affectionate caricature.",
    icon: "laugh",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "features",
        label: "What to exaggerate",
        type: "textarea",
        placeholder: "e.g. the grin, the eyebrows, the love of biscuits",
        fallback: "harmless, recognisable personality details",
      },
    ],
    mainPrompt:
      "Create a humorous caricature of the person in this photo. Exaggerate {{features}} in a playful, recognisable way while keeping the person’s identity clear. Use expressive cartoon styling, bold shapes and a funny but affectionate tone. Keep it kind. Do not mock in a cruel way.",
    outputFormat: "Return a single caricature illustration. No captions unless requested. No watermarks.",
  },
  {
    id: "cartoon-version",
    category: "fun",
    funGroup: "funny",
    name: "Cartoon Version",
    shortDescription: "A polished cartoon of the same photograph.",
    icon: "pencil",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "style",
        label: "Cartoon style",
        type: "select",
        defaultValue: "modern animation still with clean lines",
        options: [
          { value: "modern animation still with clean lines", label: "Modern animation" },
          { value: "classic newspaper-strip ink and colour", label: "Newspaper strip" },
          { value: "soft storybook illustration", label: "Storybook" },
          { value: "bold Saturday-morning cartoon", label: "Saturday morning" },
        ],
      },
    ],
    mainPrompt:
      "Transform this photo into a polished cartoon illustration. Preserve the subject’s recognisable identity, pose, clothing and composition while using {{style}}, expressive linework, colour and texture.",
    outputFormat: "Return a single cartoon illustration of the original scene. No watermarks.",
  },
  {
    id: "comic-book-hero",
    category: "fun",
    funGroup: "funny",
    name: "Comic Book Hero",
    shortDescription: "A dramatic illustrated hero portrait.",
    icon: "shield",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "powers",
        label: "Costume, powers or setting",
        type: "text",
        placeholder: "e.g. garden-cape, tea-based powers, rainy rooftop",
        fallback: "a heroic costume and setting that suits the person",
      },
    ],
    mainPrompt:
      "Transform this photo into a dramatic comic-book hero portrait. Preserve the subject’s recognisable identity and key features. Add {{powers}}, bold lighting, cinematic composition and illustrated comic-book detail.",
    outputFormat: "Return a single comic-book portrait. No extra panels unless asked. No watermarks.",
  },
  {
    id: "overly-serious-photo",
    category: "fun",
    funGroup: "funny",
    name: "Overly Serious Official Photo",
    shortDescription: "An absurdly formal portrait for a made-up club.",
    icon: "meh",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "organisation",
        label: "Fictional club or organisation",
        type: "text",
        placeholder: "e.g. The Royal Society of Biscuits",
        fallback: "a deadpan imaginary organisation",
      },
    ],
    mainPrompt:
      "Turn this image into an absurdly serious official-looking portrait for {{organisation}}. Preserve the person’s identity and appearance, but use an exaggeratedly formal pose, plain background and deadpan expression. Keep it photorealistic and humorous. A small discreet organisation name is allowed if it stays readable.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "victorian-portrait",
    category: "fun",
    funGroup: "funny",
    name: "Victorian Portrait",
    shortDescription: "A formal historical studio portrait.",
    icon: "landmark",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this photo into a formal Victorian-era portrait. Preserve the person’s recognisable identity while changing the clothing, setting, lighting and photographic style to match the period. Use realistic historical detail and a slightly serious portrait expression.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Weird & Wonderful ——
  {
    id: "giant-or-tiny",
    category: "fun",
    funGroup: "weird",
    name: "Giant Me / Tiny Me",
    shortDescription: "A convincing change of scale in the scene.",
    icon: "maximize",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "scale",
        label: "Scale",
        type: "select",
        defaultValue: "tiny",
        options: [
          { value: "tiny", label: "Tiny" },
          { value: "giant", label: "Giant" },
        ],
      },
    ],
    mainPrompt:
      "Create a surreal but photorealistic version of this image where I am {{scale}} in relation to the surrounding environment. Preserve my recognisable identity, clothing and key details. Make the scale difference convincing through realistic perspective, lighting, shadows and interaction with the scene.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "pet-to-human",
    category: "fun",
    funGroup: "weird",
    name: "Pet-to-Human",
    shortDescription: "Reimagine a pet as a person with the same spirit.",
    icon: "paw",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Reimagine this pet as a human while preserving its distinctive personality, colouring, markings and expression. Create a realistic human character with clothing, hairstyle, pose and setting that reflect the pet’s appearance and temperament. Do not copy a famous person.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "human-to-pet",
    category: "fun",
    funGroup: "weird",
    name: "Human-to-Pet",
    shortDescription: "A playful animal portrait of the same person.",
    icon: "cat",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "animal",
        label: "Animal",
        type: "select",
        defaultValue: "cat",
        options: [
          { value: "cat", label: "Cat" },
          { value: "dog", label: "Dog" },
          { value: "rabbit", label: "Rabbit" },
          { value: "fox", label: "Fox" },
          { value: "owl", label: "Owl" },
        ],
      },
    ],
    mainPrompt:
      "Reimagine the person in this image as a {{animal}} while preserving recognisable personality cues, colouring, expression and key visual characteristics. Create a playful but realistic animal portrait.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "impossible-scene",
    category: "fun",
    funGroup: "weird",
    name: "Floating / Impossible Scene",
    shortDescription: "A photorealistic impossible event.",
    icon: "cloud",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "event",
        label: "Impossible event",
        type: "textarea",
        placeholder: "e.g. calmly floating above the garden with teacups in orbit",
        fallback: "a gentle, surreal levitation in the original setting",
      },
    ],
    mainPrompt:
      "Transform this image into a surreal, photorealistic scene where {{event}}. Preserve the subject’s recognisable identity and key appearance. Make the lighting, shadows, perspective and interaction with the environment realistic.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "swap-the-world",
    category: "fun",
    funGroup: "weird",
    name: "Swap the World",
    shortDescription: "Keep the person, change the entire setting.",
    icon: "globe",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "location",
        label: "New location",
        type: "text",
        placeholder: "e.g. a submarine galley, the moon, a 1930s ballroom",
        fallback: "an unexpected but photorealistic location",
      },
    ],
    mainPrompt:
      "Keep the subject recognisable but place them in a completely unexpected environment: {{location}}. Preserve their identity, clothing and pose while making the new setting realistic and visually coherent.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "fantasy-sidekick",
    category: "fun",
    funGroup: "weird",
    name: "Animal Companion",
    shortDescription: "Add a creature that belongs in the scene.",
    icon: "bird",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "companion",
        label: "Companion",
        type: "text",
        placeholder: "e.g. a ginger cat, a tiny dragon, a polite fox",
        fallback: "a friendly animal companion that suits the scene",
      },
    ],
    mainPrompt:
      "Add a realistic {{companion}} beside the subject. Preserve the subject’s identity, pose and appearance. Make the companion fit naturally into the scene with matching lighting, shadows, scale and perspective. Do not replace the subject.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Movie & Poster Maker ——
  {
    id: "fake-movie-poster",
    category: "fun",
    funGroup: "movie",
    name: "Fake Movie Poster",
    shortDescription: "A cinematic poster starring this photograph.",
    icon: "drama",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "title",
        label: "Film title",
        type: "text",
        placeholder: "e.g. The Last Biscuit",
        fallback: "a fitting fictional film title",
      },
      {
        id: "genre",
        label: "Genre",
        type: "select",
        defaultValue: "spy thriller",
        options: [
          { value: "spy thriller", label: "Spy thriller" },
          { value: "rom-com", label: "Rom-com" },
          { value: "disaster movie", label: "Disaster movie" },
          { value: "western", label: "Western" },
          { value: "space opera", label: "Space opera" },
          { value: "family adventure", label: "Family adventure" },
        ],
      },
      {
        id: "tagline",
        label: "Tagline",
        type: "text",
        placeholder: "e.g. Some crumbs never settle.",
        fallback: "a short cinematic tagline",
      },
    ],
    mainPrompt:
      "Create a cinematic movie poster using this photograph as the main character reference. Preserve the subject’s recognisable identity. Add the fictional film title {{title}}, genre {{genre}}, tagline {{tagline}}, cinematic lighting, dramatic composition and professional poster typography. Make it look like a real promotional poster for a fictional film.",
    outputFormat: POSTER_OUTPUT,
  },
  {
    id: "eighties-movie-poster",
    category: "fun",
    funGroup: "movie",
    name: "1980s Movie Poster",
    shortDescription: "A vintage painted-poster look from the eighties.",
    icon: "ticket",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "title",
        label: "Film title",
        type: "text",
        placeholder: "e.g. Night Shift at the Garden Centre",
        fallback: "a fitting 1980s film title",
      },
      {
        id: "genre",
        label: "Genre",
        type: "select",
        defaultValue: "adventure",
        options: [
          { value: "adventure", label: "Adventure" },
          { value: "action", label: "Action" },
          { value: "teen comedy", label: "Teen comedy" },
          { value: "sci-fi", label: "Sci-fi" },
          { value: "horror", label: "Horror" },
        ],
      },
    ],
    mainPrompt:
      "Transform this image into a fictional 1980s movie poster. Preserve the subject’s recognisable identity. Add era-appropriate clothing, typography, colour grading, film grain, dramatic lighting and vintage poster design. Use the title {{title}} and genre {{genre}}.",
    outputFormat: POSTER_OUTPUT,
  },
  {
    id: "streaming-series-poster",
    category: "fun",
    funGroup: "movie",
    name: "Fake Streaming-Series Poster",
    shortDescription: "A premium series key art from this portrait.",
    icon: "tv",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "title",
        label: "Series title",
        type: "text",
        placeholder: "e.g. Moreton",
        fallback: "a fitting series title",
      },
      {
        id: "tagline",
        label: "Tagline",
        type: "text",
        placeholder: "e.g. Some secrets grow in the garden.",
        fallback: "a short series tagline",
      },
    ],
    mainPrompt:
      "Create a premium fictional streaming-series poster using this portrait. Preserve the subject’s identity. Add cinematic lighting, dramatic composition, title typography and a genre-appropriate visual style. Use the title {{title}} and tagline {{tagline}}.",
    outputFormat: POSTER_OUTPUT,
  },
  {
    id: "movie-character-casting",
    category: "fun",
    funGroup: "movie",
    name: "Movie Character Casting",
    shortDescription: "Cast the subject as a fictional film character.",
    icon: "userRound",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "genre",
        label: "Genre or role",
        type: "text",
        placeholder: "e.g. 1940s detective, space mechanic, folk-horror villager",
        fallback: "a cinematic character role that suits the face",
      },
    ],
    mainPrompt:
      "Transform this image into a cinematic portrait of the subject as a fictional {{genre}} character. Preserve their recognisable identity while changing the clothing, setting, lighting and atmosphere to suit the role.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Retro & Nostalgia ——
  {
    id: "eighties-photo",
    category: "fun",
    funGroup: "retro",
    name: "1980s Photo",
    shortDescription: "An authentic-looking eighties snapshot.",
    icon: "film",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this photograph into an authentic-looking 1980s photograph. Preserve the subject’s recognisable identity. Add era-appropriate clothing, hairstyle, lighting, colours, camera characteristics and background details. Use realistic film grain and period-appropriate photographic imperfections.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "disposable-camera",
    category: "fun",
    funGroup: "retro",
    name: "1990s Disposable Camera",
    shortDescription: "A candid late-nineties film memory.",
    icon: "camera",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Turn this photo into a candid late-1990s disposable-camera memory. Add natural film grain, slight motion blur, uneven flash exposure, warm colour shifts and subtle imperfections. Preserve the subject’s recognisable identity and the original moment.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "ccd-camera",
    category: "fun",
    funGroup: "retro",
    name: "Early-2000s CCD Camera",
    shortDescription: "Compact-camera flash, noise and all.",
    icon: "aperture",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this image into an early-2000s compact digital camera photograph. Add direct flash, slightly blown highlights, realistic low-light noise, subtle colour shifts and authentic CCD-style detail. Preserve the subject’s identity and the original composition.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "vhs-still",
    category: "fun",
    funGroup: "retro",
    name: "VHS / Camcorder Still",
    shortDescription: "A frame from a 1990s home video.",
    icon: "cassette",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this image into a realistic still frame from a 1990s home video. Add soft focus, interlacing-style texture, muted colour, slight motion blur and authentic camcorder lighting. Preserve the subject’s recognisable identity and the original scene.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "old-family-album",
    category: "fun",
    funGroup: "retro",
    name: "Old Family Album",
    shortDescription: "A believable album print from another decade.",
    icon: "album",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "decade",
        label: "Decade",
        type: "select",
        defaultValue: "1970s",
        options: [
          { value: "1950s", label: "1950s" },
          { value: "1960s", label: "1960s" },
          { value: "1970s", label: "1970s" },
          { value: "1980s", label: "1980s" },
          { value: "1990s", label: "1990s" },
        ],
      },
    ],
    mainPrompt:
      "Transform this image into a believable old family-album photograph from the {{decade}}. Preserve the subject’s recognisable identity, pose and important details. Use period-appropriate colour, clothing, lighting, film texture and photographic imperfections.",
    outputFormat: DEFAULT_OUTPUT,
  },

  // —— Collages & Memories ——
  {
    id: "scrapbook-collage",
    category: "fun",
    funGroup: "collages",
    printGroup: "memories",
    name: "Scrapbook Collage",
    shortDescription: "The photo on a real scrapbook page.",
    icon: "sticky",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "details",
        label: "Page extras",
        type: "select",
        defaultValue: "paper texture, washi tape, a few stamps and a short caption",
        options: [
          {
            value: "paper texture, washi tape, a few stamps and a short caption",
            label: "Tape, stamps and caption",
          },
          {
            value: "dried flowers, handwriting and kraft paper",
            label: "Dried flowers",
          },
          {
            value: "ticket stubs, stickers and a date in the margin",
            label: "Tickets and date",
          },
        ],
      },
    ],
    mainPrompt:
      "Create a beautiful scrapbook-style collage using the supplied photograph. Preserve the original image as the main subject. Add {{details}} in a cohesive, realistic scrapbook layout. Keep the photograph itself unchanged.",
    outputFormat:
      "Return a single scrapbook page. The original photograph must remain unaltered inside the layout. No watermarks.",
  },
  {
    id: "polaroid-memory",
    category: "fun",
    funGroup: "collages",
    printGroup: "memories",
    name: "Polaroid Memory",
    shortDescription: "An instant print with a handwritten caption.",
    icon: "stamp",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "caption",
        label: "Handwritten caption",
        type: "text",
        placeholder: "e.g. Sunday with Maisy",
        fallback: "a short handwritten date",
      },
    ],
    mainPrompt:
      "Turn this image into a realistic Polaroid-style memory photograph. Add a white instant-film border, subtle film texture, natural colour and a handwritten caption reading {{caption}}. Preserve the original subject and composition.",
    outputFormat:
      "Return a single Polaroid-framed photograph. The caption must be spelled exactly as given. No extra collage.",
  },
  {
    id: "then-and-now",
    category: "fun",
    funGroup: "collages",
    name: "Then & Now",
    shortDescription: "A clear split comparison beside this photograph.",
    icon: "arrows",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "version",
        label: "Show alongside",
        type: "select",
        defaultValue: "an older version of the same person",
        options: [
          { value: "an older version of the same person", label: "Older version" },
          { value: "a younger version of the same person", label: "Younger version" },
          { value: "a historical version of the same person", label: "Historical version" },
        ],
      },
    ],
    mainPrompt:
      "Create a visually coherent split image showing {{version}} alongside the supplied photograph. Preserve the person’s recognisable identity and make the comparison clear and realistic. Label the two sides lightly if needed: Then and Now.",
    outputFormat:
      "Return a single split image. Both sides must show the same recognisable person. No watermarks.",
  },
  {
    id: "memory-board",
    category: "fun",
    funGroup: "collages",
    name: "Memory Board",
    shortDescription: "A printable board of photographs and notes.",
    icon: "images",
    identityPreservation: "creative",
    version: 1,
    active: true,
    extraImages: 2,
    fields: [
      {
        id: "theme",
        label: "Theme, captions or dates",
        type: "text",
        placeholder: "e.g. summer 2026, garden days, quiet captions",
        fallback: "a simple family-memory theme with light captions",
      },
    ],
    mainPrompt:
      "Create a tasteful memory-board collage using these supplied photographs. Preserve each original photograph without altering the people or important details. Arrange them with {{theme}} in a cohesive, printable layout.",
    outputFormat:
      "Return a single printable memory-board layout. Do not restyle the faces inside each photograph. No watermarks.",
  },
  {
    id: "giant-object",
    category: "fun",
    funGroup: "weird",
    name: "Giant Object",
    shortDescription: "Make one object enormous. Keep the scene real.",
    icon: "maximize",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "object",
        label: "Object to enlarge",
        type: "text",
        required: true,
        placeholder: "e.g. the teacup, the garden gnome, the biscuit",
      },
    ],
    mainPrompt:
      "Make this selected object enormous while keeping the rest of the scene photorealistic: {{object}}. Preserve people and other objects at their original scale. Use convincing perspective, shadows, contact with the ground and lighting so the giant object belongs in the photograph.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "statue-version",
    category: "fun",
    funGroup: "weird",
    name: "Turn Me into a Statue",
    shortDescription: "Marble, bronze or stone. Same person.",
    icon: "landmark",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "material",
        label: "Material",
        type: "select",
        defaultValue: "white marble",
        options: [
          { value: "white marble", label: "Marble" },
          { value: "bronze", label: "Bronze" },
          { value: "weathered stone", label: "Stone" },
          { value: "gold leaf statue", label: "Gold" },
        ],
      },
    ],
    mainPrompt:
      "Transform the main subject into a statue made of {{material}} while preserving recognisable identity, pose and proportions. The result should look like a real sculpture photographed in a fitting setting, with realistic material, weathering and lighting. Not a plastic filter.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "miniature-diorama",
    category: "fun",
    funGroup: "toys",
    name: "Miniature Diorama",
    shortDescription: "The whole scene as a detailed model.",
    icon: "box",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform the entire scene into a detailed miniature diorama or model, as if photographed on a modeller’s workbench. Preserve recognisable people, clothing and layout. Use realistic miniature materials, scale, tilt-shift depth of field and display lighting. Still a photograph of a model, not a cartoon.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "surreal-dreamscape",
    category: "fun",
    funGroup: "worlds",
    name: "Surreal Dreamscape",
    shortDescription: "An imaginative dream. Same main subject.",
    icon: "moon",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "mood",
        label: "Dream mood",
        type: "text",
        placeholder: "e.g. quiet floating rooms, a garden of clocks",
        fallback: "a poetic, slightly impossible dream of the original scene",
      },
    ],
    mainPrompt:
      "Create an imaginative surreal dreamscape from this photograph: {{mood}}. Retain the main subject’s recognisable identity. The scene may change substantially, but should feel like one coherent dream with believable light and atmosphere.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "absurd-weather",
    category: "fun",
    funGroup: "worlds",
    name: "Absurd Weather",
    shortDescription: "Bizarre weather that still photographs as real.",
    icon: "cloud",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "weather",
        label: "Weather",
        type: "text",
        required: true,
        placeholder: "e.g. giant soap bubbles, falling rubber ducks, confetti storm",
      },
    ],
    mainPrompt:
      "Add bizarre but visually believable weather to this scene: {{weather}}. Keep people and the original location recognisable. Make the weather interact with the environment through realistic lighting, shadows, wetness or motion. Still a photograph.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "upside-down-world",
    category: "fun",
    funGroup: "worlds",
    name: "Upside-Down World",
    shortDescription: "A physically coherent inverted scene.",
    icon: "rotate",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Create a physically coherent upside-down version of this scene, as if gravity had reversed. Preserve recognisable people and key objects. Recalculate contact, hanging, lighting and shadows so the inverted world looks photographed, not simply flipped.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "fantasy-adventure",
    category: "fun",
    funGroup: "worlds",
    name: "Fantasy Adventure",
    shortDescription: "A cinematic fantasy version of this place.",
    icon: "wand",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "world",
        label: "Fantasy world",
        type: "text",
        placeholder: "e.g. misty elven woods, a cliff-top citadel",
        fallback: "a cinematic high-fantasy version of the original setting",
      },
    ],
    mainPrompt:
      "Transform this scene into a cinematic fantasy adventure: {{world}}. Keep the main subject recognisable. Use dramatic natural light, costume and environment that still feel photographed.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "scifi-future",
    category: "fun",
    funGroup: "worlds",
    name: "Sci-Fi Future",
    shortDescription: "The same place, years ahead.",
    icon: "tv",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this scene into a believable futuristic version of itself. Keep the main subject recognisable. Add plausible future architecture, lighting and technology without turning it into a cartoon or a different person.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "medieval-version",
    category: "fun",
    funGroup: "worlds",
    name: "Medieval Version",
    shortDescription: "A historically inspired medieval scene.",
    icon: "clock",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this scene into a historically inspired medieval environment. Keep the main subject recognisable. Use period-plausible clothing, architecture, materials and daylight. Photorealistic, not a theme-park cartoon.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "space-version",
    category: "fun",
    funGroup: "worlds",
    name: "Space Version",
    shortDescription: "A believable space-themed environment.",
    icon: "globe",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this scene into a believable space-themed environment, such as a station, craft interior or planetary outlook. Keep the main subject recognisable. Lighting, reflections and scale should feel photographed.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "underwater-world",
    category: "fun",
    funGroup: "worlds",
    name: "Underwater World",
    shortDescription: "The scene, submerged and still photographic.",
    icon: "droplets",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this scene into a realistic underwater environment. Keep the main subject recognisable. Use caustic light, suspended particles, colour falloff and buoyancy so it looks like a real underwater photograph.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "motion-long-exposure",
    category: "fun",
    funGroup: "worlds",
    name: "Motion / Long Exposure",
    shortDescription: "Light trails and motion. The main subject stays.",
    icon: "rotate",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "motion",
        label: "What should streak",
        type: "text",
        placeholder: "e.g. car lights, a fountain, people walking by",
        fallback: "gentle motion in the background while the main subject stays readable",
      },
    ],
    mainPrompt:
      "Create a creative long-exposure interpretation of this photograph. Motion: {{motion}}. Retain the main subject’s recognisable identity. The result should still feel like a photograph, with realistic light trails and motion blur where asked.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "pixel-art",
    category: "fun",
    funGroup: "funny",
    name: "Pixel Art",
    shortDescription: "A detailed pixel-art version of the subject.",
    icon: "blocks",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this image into detailed pixel art. Keep the subject recognisable through colour, silhouette and key features. Use clean pixels, a limited but rich palette, and a finished sprite-sheet quality. Not a blurry mosaic filter.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "clay-stop-motion",
    category: "fun",
    funGroup: "toys",
    name: "Clay / Stop-Motion Character",
    shortDescription: "A claymation figure of the same person.",
    icon: "puzzle",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Turn the subject into a clay or stop-motion-style character, as if photographed on a miniature set. Preserve recognisable facial features, hair and clothing colours. Use real clay texture, fingerprints, studio lighting and a handmade look.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "sticker-version",
    category: "fun",
    funGroup: "funny",
    name: "Sticker Version",
    shortDescription: "A clean die-cut sticker of the subject.",
    icon: "stamp",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Create a clean sticker-style version of the main subject, with a simple white die-cut border and a flat or softly illustrated look. Keep the person recognisable. No extra scene, no watermark.",
    outputFormat:
      "Return a single sticker graphic on a plain light background, with a clear cut-line. No watermarks.",
  },
  {
    id: "trading-card",
    category: "fun",
    funGroup: "toys",
    name: "Trading Card",
    shortDescription: "A fictional collectible card of this person.",
    icon: "ticket",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "name",
        label: "Card name",
        type: "text",
        placeholder: "e.g. Garden Keeper",
        fallback: "a fitting character name",
      },
      {
        id: "stats",
        label: "Optional stats or title",
        type: "text",
        placeholder: "e.g. Rare · Horticulture 9",
        fallback: "a short playful title",
      },
    ],
    mainPrompt:
      "Turn the subject into a fictional collectible trading card. Card name: {{name}}. Title or stats: {{stats}}. Preserve recognisable identity. Use premium card layout, readable typography spelled exactly as given, and photographic or painted portrait art of the same person.",
    outputFormat:
      "Return a single trading-card design. Name and stats must be spelled exactly as given. No watermarks.",
  },
  {
    id: "yearbook-version",
    category: "fun",
    funGroup: "retro",
    name: "Yearbook Version",
    shortDescription: "A nostalgic school portrait of the same person.",
    icon: "album",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "era",
        label: "Era",
        type: "select",
        defaultValue: "1990s school portrait",
        options: [
          { value: "1980s school portrait", label: "1980s" },
          { value: "1990s school portrait", label: "1990s" },
          { value: "early-2000s school portrait", label: "Early 2000s" },
        ],
      },
    ],
    mainPrompt:
      "Create a nostalgic yearbook or school portrait from this photograph: {{era}}. Keep the person’s recognisable identity. Use typical yearbook lighting, mottled studio backdrop, slightly formal pose and period photographic character. Still the same person, not a different student.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "double-exposure",
    category: "fun",
    funGroup: "weird",
    name: "Double Exposure",
    shortDescription: "Two images, one photographic blend.",
    icon: "layers",
    identityPreservation: "creative",
    version: 1,
    active: true,
    extraImages: 1,
    fields: [
      {
        id: "second",
        label: "Second subject if no extra photo",
        type: "text",
        placeholder: "e.g. a garden, the sea, a city skyline",
        fallback: "a fitting second exposure suggested by the photograph",
      },
    ],
    mainPrompt:
      "Create a photographic double exposure. Blend this portrait with {{second}} (or the extra photograph if supplied). Keep the main person recognisable. Use analogue multiple-exposure character, not a cheap overlay.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "light-leak",
    category: "fun",
    funGroup: "retro",
    name: "Light Leak / Film Soup",
    shortDescription: "Analogue leaks and soaked-film colour.",
    icon: "aperture",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Add realistic analogue light leaks and optional film-soup colour shifts to this photograph. Keep the subject recognisable. Use true film-edge burns, not a sticker overlay.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "newspaper-front",
    category: "fun",
    funGroup: "movie",
    name: "Newspaper Front Page",
    shortDescription: "A fictional newspaper splash with this photo.",
    icon: "fileText",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "headline",
        label: "Headline",
        type: "text",
        required: true,
        placeholder: "e.g. LOCAL GARDEN WINS THE STREET",
      },
      {
        id: "paper",
        label: "Paper name",
        type: "text",
        placeholder: "e.g. The Moreton Echo",
        fallback: "an original local paper name",
      },
    ],
    mainPrompt:
      "Create a realistic newspaper front page featuring this photograph. Paper name: {{paper}}. Headline: {{headline}}. Preserve the people in the photograph. Original paper only — do not copy a real newspaper’s masthead. Print halftone, columns and a believable date.",
    outputFormat:
      "Return a single newspaper front page. Headline and paper name spelled exactly as given. No watermarks.",
  },
  {
    id: "postage-stamp",
    category: "fun",
    funGroup: "toys",
    name: "Postage Stamp",
    shortDescription: "A commemorative stamp of this person or scene.",
    icon: "stamp",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "country",
        label: "Country or issue",
        type: "text",
        placeholder: "e.g. Wirral",
        fallback: "an original fictional issue",
      },
    ],
    mainPrompt:
      "Turn this photograph into a commemorative postage stamp for {{country}}. Preserve recognisable identity. Include perforations, a denomination and print texture. Original design only.",
    outputFormat:
      "Return a single postage-stamp design with a white margin. No watermarks.",
  },
  {
    id: "banknote",
    category: "fun",
    funGroup: "toys",
    name: "Banknote",
    shortDescription: "A fictional banknote portrait.",
    icon: "ticket",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "value",
        label: "Value and currency",
        type: "text",
        placeholder: "e.g. 10 Garden Pounds",
        fallback: "Ten Units",
      },
    ],
    mainPrompt:
      "Create a fictional banknote using this person as the portrait. Value: {{value}}. Preserve recognisable identity. Engraved look, serial numbers and ornamental borders. Original currency only — do not copy a real banknote.",
    outputFormat:
      "Return a single banknote design. Value spelled exactly as given. No watermarks of this app.",
  },
  {
    id: "pub-sign",
    category: "fun",
    funGroup: "funny",
    name: "Pub Sign",
    shortDescription: "A painted British pub sign of this person or scene.",
    icon: "landmark",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "name",
        label: "Pub name",
        type: "text",
        required: true,
        placeholder: "e.g. The Pig and Whistle",
      },
    ],
    mainPrompt:
      "Turn the subject into a hanging painted British pub sign named {{name}}. Preserve recognisable identity in the painted portrait. Weathered wood, iron brackets and outdoor light. Still a photograph of a real sign.",
    outputFormat:
      "Return a single photograph of the pub sign. The name must be spelled exactly as given.",
  },
  {
    id: "anime-still",
    category: "fun",
    funGroup: "funny",
    name: "Anime Still",
    shortDescription: "An original illustrated still of the same person.",
    icon: "paintbrush",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this photograph into an original hand-painted anime-style still of the same person. Keep recognisable facial identity, hair and clothing colours. Do not copy any existing studio’s characters, films or trademarked designs. Cinematic still, not a screenshot.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "cctv-still",
    category: "fun",
    funGroup: "weird",
    name: "Security Camera Still",
    shortDescription: "A CCTV frame of this scene.",
    icon: "scanEye",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this image into a realistic CCTV or security-camera still: slight wide angle, timestamp bar, modest noise and night-or-day camera colour. Keep the people recognisable. Do not invent a crime.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "thermal-view",
    category: "fun",
    funGroup: "weird",
    name: "Thermal View",
    shortDescription: "A thermal-camera look at the same scene.",
    icon: "sun",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform this image into a realistic thermal-camera view of the same scene. Keep the silhouette and identity readable. Use a photographic thermal palette, not a posterised filter.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "clone-me",
    category: "fun",
    funGroup: "weird",
    name: "Clone Me",
    shortDescription: "The same person twice in this scene.",
    icon: "images",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "where",
        label: "Where should the double stand",
        type: "text",
        placeholder: "e.g. on the left, sitting on the wall",
        fallback: "beside the original person, naturally in the scene",
      },
    ],
    mainPrompt:
      "Add a second instance of the same person {{where}}. Both must share identity, face, clothing style, lighting, scale and photographic quality. Do not invent a different person. The rest of the scene stays.",
    outputFormat: DEFAULT_OUTPUT,
  },
];
