import type { LucideIcon } from "lucide-react";
import {
  Album,
  Aperture,
  ArrowUpDown,
  Bandage,
  Bird,
  Blocks,
  Box,
  Briefcase,
  Calendar,
  Camera,
  Car,
  CassetteTape,
  Cat,
  Clapperboard,
  Clock,
  Cloud,
  Contrast,
  Crop,
  Drama,
  Droplets,
  Eraser,
  Expand,
  Eye,
  FileText,
  Film,
  Focus,
  Frame,
  Gift,
  Globe,
  History,
  House,
  ImageOff,
  Images,
  Lamp,
  Landmark,
  Laugh,
  Layers,
  LayoutGrid,
  Mail,
  Maximize2,
  Meh,
  Moon,
  Mountain,
  Move3d,
  Music,
  Package,
  Palette,
  Paintbrush,
  PawPrint,
  Pencil,
  PenTool,
  PersonStanding,
  Printer,
  Puzzle,
  Ratio,
  RotateCcw,
  ScanEye,
  ScanFace,
  ScanSearch,
  Shield,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Stamp,
  StickyNote,
  Sun,
  Ticket,
  TvMinimalPlay,
  Type,
  User,
  UserRound,
  UserX,
  Utensils,
  Wand,
} from "lucide-react";
import type { IconKey } from "./types";

export const ICONS: Record<IconKey, LucideIcon> = {
  smile: Smile,
  shirt: Shirt,
  clock: Clock,
  clapperboard: Clapperboard,
  personStanding: PersonStanding,
  sliders: SlidersHorizontal,
  crop: Crop,
  frame: Frame,
  imageOff: ImageOff,
  aperture: Aperture,
  eraser: Eraser,
  wand: Wand,
  history: History,
  bandage: Bandage,
  droplets: Droplets,
  scanSearch: ScanSearch,
  user: User,
  briefcase: Briefcase,
  sun: Sun,
  palette: Palette,
  film: Film,
  camera: Camera,
  contrast: Contrast,
  layers: Layers,
  mail: Mail,
  printer: Printer,
  layoutGrid: LayoutGrid,
  package: Package,
  gift: Gift,
  box: Box,
  blocks: Blocks,
  laugh: Laugh,
  pencil: Pencil,
  shield: Shield,
  meh: Meh,
  landmark: Landmark,
  maximize: Maximize2,
  paw: PawPrint,
  cat: Cat,
  cloud: Cloud,
  globe: Globe,
  bird: Bird,
  drama: Drama,
  ticket: Ticket,
  tv: TvMinimalPlay,
  userRound: UserRound,
  cassette: CassetteTape,
  album: Album,
  sticky: StickyNote,
  stamp: Stamp,
  images: Images,
  arrows: ArrowUpDown,
  puzzle: Puzzle,
  ratio: Ratio,
  expand: Expand,
  userX: UserX,
  type: Type,
  eye: Eye,
  scanEye: ScanEye,
  scanFace: ScanFace,
  rotate: RotateCcw,
  lamp: Lamp,
  shoppingBag: ShoppingBag,
  move3d: Move3d,
  focus: Focus,
  paintbrush: Paintbrush,
  penTool: PenTool,
  calendar: Calendar,
  mountain: Mountain,
  moon: Moon,
  house: House,
  car: Car,
  sparkles: Sparkles,
  music: Music,
  utensils: Utensils,
  fileText: FileText,
};
