import { DEFAULT_OUTPUT } from "./identity";
import type { PortraitGroupDefinition, ToolDefinition } from "./types";

export const PORTRAIT_GROUPS: PortraitGroupDefinition[] = [
  {
    id: "studio",
    name: "Studio Portraits",
    description: "Controlled light, seamless backgrounds, magazine-calm.",
  },
  {
    id: "editorial",
    name: "Editorial & Fashion",
    description: "Campaign energy, flash, black-and-white and close-ups.",
  },
  {
    id: "branding",
    name: "Professional & Personal Branding",
    description: "Headshots, café work shots and outdoor portraits.",
  },
  {
    id: "finishing",
    name: "Quality Finishing",
    description: "Light, lens, sharpness and editorial polish. Face stays the same.",
  },
  {
    id: "builder",
    name: "Portrait Builder",
    description: "One reusable builder. Pick purpose, setting, clothes, light and frame.",
  },
];

const PORTRAIT_OUTPUT =
  "Return a single photorealistic portrait photograph that fills the frame. No borders, watermarks, collage or on-image text. Keep the face recognisable.";

export const PORTRAIT_TOOLS: ToolDefinition[] = [
  {
    id: "studio-portrait",
    category: "portrait",
    portraitGroup: "studio",
    name: "Studio Portrait",
    shortDescription: "A calm studio portrait from an everyday photo.",
    icon: "user",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Create a professional studio portrait of the same person. Preserve identity, age, facial features and expression. Place them against a simple dark-grey seamless backdrop with soft classic portrait lighting. Keep clothing unless it is extremely casual, in which case use a simple dark shirt or blouse. Head-and-shoulders crop. Photorealistic, not retouched into a different person.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "dark-ceo-portrait",
    category: "portrait",
    portraitGroup: "studio",
    name: "Dark CEO Portrait",
    shortDescription: "Cinematic black-suit studio portrait.",
    icon: "briefcase",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Use my uploaded selfie as the only identity reference. Preserve my exact face and natural features. Create a cinematic studio portrait of me wearing a structured black suit over a black shirt. Deep charcoal background, strong softbox from camera-left, subtle rim light, relaxed confident expression, slightly turned shoulders, 85mm lens, shallow depth of field, realistic skin texture, premium business magazine photography.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "luxury-white-studio",
    category: "portrait",
    portraitGroup: "studio",
    name: "Luxury White Studio",
    shortDescription: "Ivory suit, warm seamless, understated luxury.",
    icon: "sun",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Turn my uploaded selfie into a high-end editorial portrait. Keep my face completely recognisable and unchanged. Dress me in an oversized ivory suit with a clean white shirt. Warm off-white seamless studio, soft directional light, subtle floor shadow, relaxed stance, one hand in pocket, understated luxury aesthetic, realistic skin and fabric detail, medium-format fashion photography.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "natural-window-light",
    category: "portrait",
    portraitGroup: "studio",
    name: "Window Light",
    shortDescription: "Soft daylight portrait by a window.",
    icon: "sun",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Re-light this as a natural window-light portrait of the same person. Preserve identity, clothing and expression. Soft directional daylight, gentle falloff, quiet interior. Shallow depth of field. Photorealistic, not a fashion campaign.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "low-angle-power",
    category: "portrait",
    portraitGroup: "studio",
    name: "Low-Angle Power",
    shortDescription: "Confident full-body from slightly below.",
    icon: "move3d",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Use my uploaded selfie as the identity reference. Create a low-angle full-body studio portrait that feels confident and modern. Black oversized blazer, wide-leg trousers and clean sneakers. Minimal concrete-grey studio, camera positioned slightly below waist height, strong directional light, subtle shadows, relaxed stance, premium fashion campaign photography.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "founder-at-work",
    category: "portrait",
    portraitGroup: "editorial",
    name: "Founder at Work",
    shortDescription: "Editorial desk portrait in a quiet studio.",
    icon: "briefcase",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Use my uploaded photo as the identity reference. Create an editorial portrait of me sitting at a minimalist desk in a modern creative studio. Black T-shirt, tailored trousers, laptop slightly out of focus in the foreground, natural window light from the side, calm focused expression, cinematic depth, realistic skin, premium startup founder photography.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "black-white-editorial",
    category: "portrait",
    portraitGroup: "editorial",
    name: "Black & White Editorial",
    shortDescription: "Sculpted light, film grain, chest-up.",
    icon: "contrast",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Transform my selfie into a dramatic black-and-white editorial portrait. Preserve my exact facial identity. Tight chest-up composition, black tailored jacket, textured dark-grey background, hard side light creating sculpted shadows across the face, visible skin texture, serious expression, subtle film grain, timeless luxury magazine photography.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "flash-portrait",
    category: "portrait",
    portraitGroup: "editorial",
    name: "Flash Portrait",
    shortDescription: "On-camera flash, bold contemporary editorial.",
    icon: "lamp",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Use my uploaded selfie as the identity reference. Create a bold fashion portrait shot with direct on-camera flash. Black oversized suit, plain warm-grey studio wall, slightly off-centre composition, relaxed confident pose, crisp facial detail, realistic skin texture, subtle flash shadow behind me, contemporary celebrity editorial photography.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "close-up-brand",
    category: "portrait",
    portraitGroup: "editorial",
    name: "Close-Up Brand Portrait",
    shortDescription: "85mm close-up. Pores, hair, no over-retouch.",
    icon: "focus",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Create an ultra-realistic close-up portrait from my uploaded selfie. Preserve every recognisable facial feature, skin tone and hairstyle. Black crew-neck top, muted blue-grey background, soft beauty-dish lighting, strong eye contact, natural expression, visible skin pores, individual hair strands, subtle contrast, 85mm f/2 portrait photography, polished but not over-retouched.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "professional-headshot",
    category: "portrait",
    portraitGroup: "branding",
    name: "Professional Headshot",
    shortDescription: "A clean, friendly headshot for work use.",
    icon: "briefcase",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Create a professional linked-in style headshot of the same person. Preserve identity and age. Neutral or softly lit office-studio background. Natural expression, approachable, well exposed. Subtle clothing tidy-up only. No heavy makeup, no age change, no beautifying that alters the face.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "linkedin-headshot",
    category: "portrait",
    portraitGroup: "branding",
    name: "LinkedIn Headshot",
    shortDescription: "Polished chest-up headshot with outfit you choose.",
    icon: "userRound",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "outfit",
        label: "Outfit",
        type: "select",
        defaultValue: "navy blazer",
        options: [
          { value: "navy blazer", label: "Navy blazer" },
          { value: "black suit", label: "Black suit" },
          { value: "smart-casual outfit", label: "Smart casual" },
        ],
      },
      {
        id: "shirt",
        label: "Top colour",
        type: "select",
        defaultValue: "white",
        options: [
          { value: "white", label: "White" },
          { value: "light blue", label: "Light blue" },
          { value: "black", label: "Black" },
          { value: "cream", label: "Cream" },
        ],
      },
      {
        id: "background",
        label: "Background",
        type: "select",
        defaultValue: "light gray",
        options: [
          { value: "light gray", label: "Light grey" },
          { value: "white", label: "White" },
          { value: "beige", label: "Beige" },
        ],
      },
    ],
    mainPrompt:
      "Transform this selfie into a polished LinkedIn headshot. Keep my face, skin tone, hairstyle, recognizable features accurate. Dress me in a {{outfit}} over a {{shirt}} top. Use soft studio lighting, a clean {{background}} background, natural skin texture, sharp eyes, and a confident but approachable expression. Frame it from chest up. Make it photorealistic and professionally retouched without changing my identity.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "passport-photo",
    category: "portrait",
    portraitGroup: "branding",
    name: "Passport / ID Photo",
    shortDescription: "UK 45×35 mm style. Neutral, plain background.",
    icon: "user",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Guidance only — check current passport rules before you apply.",
    mainPrompt:
      "Create a UK-style passport or ID photograph from this portrait. Plain even light-grey or off-white background, even frontal lighting, head and shoulders, face looking at the camera, mouth closed, eyes open and visible. Frame in 45 millimetre by 35 millimetre proportions. Preserve exact identity, facial structure, skin tone, hairstyle and expression. No smile exaggeration, no beautification, no shadows on the background, no glasses glare. Photorealistic.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "cafe-lifestyle",
    category: "portrait",
    portraitGroup: "branding",
    name: "Modern Café Lifestyle",
    shortDescription: "Candid window seat. Vertical personal-brand shot.",
    icon: "sticky",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "outfit",
        label: "Outfit",
        type: "text",
        placeholder: "e.g. navy knit and chinos",
        fallback: "smart casual clothes that suit the person",
      },
      {
        id: "prop",
        label: "Nearby prop",
        type: "select",
        defaultValue: "coffee cup",
        options: [
          { value: "laptop", label: "Laptop" },
          { value: "notebook", label: "Notebook" },
          { value: "coffee cup", label: "Coffee cup" },
        ],
      },
    ],
    mainPrompt:
      "Turn this selfie into a candid personal-brand photo taken inside a stylish café. Preserve my exact identity and natural appearance. Show me seated beside a window, wearing {{outfit}}, with a {{prop}} naturally positioned nearby. Use soft daylight, warm neutral colors, shallow depth of field, and an authentic mid-action expression. Keep the scene uncluttered and photorealistic. Format it vertically for Instagram.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "outdoor-golden-hour",
    category: "portrait",
    portraitGroup: "branding",
    name: "Outdoor Golden-Hour Portrait",
    shortDescription: "Warm sunlight, soft background, natural pose.",
    icon: "sun",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "place",
        label: "Place",
        type: "select",
        defaultValue: "park",
        options: [
          { value: "city street", label: "City street" },
          { value: "park", label: "Park" },
          { value: "beach", label: "Beach" },
          { value: "rooftop", label: "Rooftop" },
        ],
      },
      {
        id: "outfit",
        label: "Outfit",
        type: "text",
        placeholder: "e.g. linen shirt and dark trousers",
        fallback: "simple clothes that suit the person",
      },
    ],
    mainPrompt:
      "Create a professional outdoor portrait from this selfie. Keep my facial features, proportions, hair, and skin tone unchanged. Place me in {{place}} during golden hour, with warm sunlight outlining my hair and a softly blurred background. Dress me in {{outfit}}. Use natural posing, gentle shadows, realistic colors, and a relaxed smile. Make it look like it was shot with a professional portrait lens.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "dslr-quality",
    category: "portrait",
    portraitGroup: "finishing",
    name: "High-End DSLR Quality",
    shortDescription: "Crisp dynamic range. Face unchanged.",
    icon: "camera",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Recreate this image with the crispness, dynamic range, and depth of a high-end DSLR. Refine exposure, focus, and tonal detail while keeping my facial features, expression, and identity unchanged. Do not change clothing, pose or setting.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "studio-light-finish",
    category: "portrait",
    portraitGroup: "finishing",
    name: "Professional Studio Light",
    shortDescription: "Polished studio light. No face reshape.",
    icon: "lamp",
    identityPreservation: "strict",
    version: 1,
    active: true,
    note: "Flattering light only. The face is not to be reshaped or beautified.",
    mainPrompt:
      "Give this portrait the polished lighting of a professional studio session. Add flattering highlights, dimensional shadows, and balanced illumination while retaining my genuine complexion, structure, and original appearance. Do not interpret flattering as permission to reshape or beautify the face. Do not change clothing, pose or identity.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "premium-lens-depth",
    category: "portrait",
    portraitGroup: "finishing",
    name: "Premium Lens Depth",
    shortDescription: "Portrait-lens separation. Same person, same pose.",
    icon: "aperture",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Create realistic optical depth similar to a premium portrait lens, with refined subject separation and smooth background falloff. Keep my proportions, posture, clothing, and recognisable features exactly as captured.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "golden-hour-light",
    category: "portrait",
    portraitGroup: "finishing",
    name: "Sophisticated Golden Hour",
    shortDescription: "Warm the existing light. Keep the scene.",
    icon: "sun",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Transform the existing illumination into sophisticated golden-hour light with warm highlights, soft shadows, and natural dimensionality. Maintain my true complexion, expression, facial details, and distinctive characteristics. Do not change clothing, setting or identity.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "editorial-retouch",
    category: "portrait",
    portraitGroup: "finishing",
    name: "Refined Editorial Retouch",
    shortDescription: "Tones and cleanup. Structure stays authentic.",
    icon: "wand",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Give this image a refined editorial finish through controlled tones, subtle cleanup, and enhanced visual richness. Remove minor distractions without changing my facial structure, recognisable traits, or authentic appearance.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "luxury-magazine-portrait",
    category: "portrait",
    portraitGroup: "finishing",
    name: "Luxury Magazine Portrait",
    shortDescription: "Premium magazine finish. Identity intact.",
    icon: "drama",
    identityPreservation: "strict",
    version: 1,
    active: true,
    mainPrompt:
      "Elevate the entire frame into a premium magazine-style portrait using sophisticated illumination, controlled contrast, realistic dimensionality, and refined finishing while keeping my authentic identity completely intact. Do not invent a different person.",
    outputFormat: PORTRAIT_OUTPUT,
  },
  {
    id: "portrait-builder",
    category: "portrait",
    portraitGroup: "builder",
    name: "Portrait Builder",
    shortDescription: "Choose purpose, setting, clothes, light, frame and ratio.",
    icon: "sliders",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    note: "One builder for any combination. The face stays yours.",
    fields: [
      {
        id: "purpose",
        label: "Purpose",
        type: "select",
        defaultValue: "LinkedIn / Professional",
        options: [
          { value: "LinkedIn / Professional", label: "LinkedIn / Professional" },
          { value: "Social Media", label: "Social Media" },
          { value: "Personal Branding", label: "Personal Branding" },
          { value: "Travel", label: "Travel" },
          { value: "Family", label: "Family" },
          { value: "Couple", label: "Couple" },
          { value: "Creative / Editorial", label: "Creative / Editorial" },
          { value: "Studio Portrait", label: "Studio Portrait" },
        ],
      },
      {
        id: "setting",
        label: "Setting",
        type: "select",
        defaultValue: "Studio",
        options: [
          { value: "Studio", label: "Studio" },
          { value: "Café", label: "Café" },
          { value: "Office", label: "Office" },
          { value: "Outdoor", label: "Outdoor" },
          { value: "Beach", label: "Beach" },
          { value: "City", label: "City" },
          { value: "Park", label: "Park" },
          { value: "Rooftop", label: "Rooftop" },
          { value: "Home", label: "Home" },
          { value: "Custom", label: "Custom" },
        ],
      },
      {
        id: "customSetting",
        label: "Custom setting",
        type: "text",
        placeholder: "Only if setting is Custom",
        fallback: "none — use the selected setting",
      },
      {
        id: "clothing",
        label: "Clothing",
        type: "select",
        defaultValue: "Smart casual",
        options: [
          { value: "Smart casual", label: "Smart casual" },
          { value: "Suit", label: "Suit" },
          { value: "Blazer", label: "Blazer" },
          { value: "Shirt", label: "Shirt" },
          { value: "Knitwear", label: "Knitwear" },
          { value: "T-shirt", label: "T-shirt" },
          { value: "Custom", label: "Custom" },
        ],
      },
      {
        id: "customClothing",
        label: "Custom clothing",
        type: "text",
        placeholder: "Only if clothing is Custom",
        fallback: "none — use the selected clothing",
      },
      {
        id: "lighting",
        label: "Lighting",
        type: "select",
        defaultValue: "Soft studio",
        options: [
          { value: "Soft studio", label: "Soft studio" },
          { value: "Window light", label: "Window light" },
          { value: "Golden hour", label: "Golden hour" },
          { value: "Dramatic", label: "Dramatic" },
          { value: "Flash", label: "Flash" },
          { value: "Natural daylight", label: "Natural daylight" },
          { value: "Black and white", label: "Black and white" },
        ],
      },
      {
        id: "framing",
        label: "Framing",
        type: "select",
        defaultValue: "Head and shoulders",
        options: [
          { value: "Close-up", label: "Close-up" },
          { value: "Head and shoulders", label: "Head and shoulders" },
          { value: "Chest-up", label: "Chest-up" },
          { value: "Waist-up", label: "Waist-up" },
          { value: "Full-body", label: "Full-body" },
        ],
      },
      {
        id: "aspect",
        label: "Aspect ratio",
        type: "select",
        defaultValue: "Portrait 4:5",
        options: [
          { value: "Square 1:1", label: "Square" },
          { value: "Portrait 4:5", label: "Portrait 4:5" },
          { value: "Instagram Story 9:16", label: "Instagram Story 9:16" },
          { value: "LinkedIn profile crop", label: "LinkedIn profile" },
          { value: "Landscape 3:2", label: "Landscape" },
          { value: "Custom", label: "Custom" },
        ],
      },
      {
        id: "customAspect",
        label: "Custom aspect ratio",
        type: "text",
        placeholder: "e.g. 5:4",
        fallback: "none — use the selected ratio",
      },
    ],
    mainPrompt:
      "Use the uploaded photograph as the only identity reference. Create a photorealistic {{purpose}} portrait of the same person. Setting: {{setting}}. Custom setting notes: {{customSetting}}. Clothing: {{clothing}}. Custom clothing notes: {{customClothing}}. Lighting: {{lighting}}. Framing: {{framing}}. Aspect ratio: {{aspect}}. Custom aspect notes: {{customAspect}}. Preserve recognisable identity, facial features, natural skin tone, hairstyle, expression and proportions. Do not reshape, beautify or redesign the face. Do not invent facial features. Realistic skin and fabric. The result must look like a real photograph of this person, not a different person.",
    outputFormat: PORTRAIT_OUTPUT,
  },
];
