import { DEFAULT_OUTPUT } from "./identity";
import type { PrintGroupDefinition, ToolDefinition } from "./types";

export const PRINT_GROUPS: PrintGroupDefinition[] = [
  {
    id: "memories",
    name: "Memories",
    description: "Scrapbooks, Polaroids and photo-booth strips.",
  },
  {
    id: "collages",
    name: "Collages",
    description: "Several photographs on one page. Originals stay intact.",
  },
  {
    id: "cards",
    name: "Cards & Print",
    description: "Cards, postcards, wall art, calendars and print layouts.",
  },
];

const PRINT_OUTPUT =
  "Return a single print-ready image. Any lettering must be spelled exactly as given and stay readable. No watermarks. Do not alter faces inside the photographs.";

export const PRINT_TOOLS: ToolDefinition[] = [
  {
    id: "collage-maker",
    category: "print",
    printGroup: "collages",
    name: "Collage Maker",
    shortDescription: "Combine photographs into one printed page.",
    icon: "layers",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    extraImages: 2,
    fields: [
      {
        id: "layout",
        label: "Layout",
        type: "select",
        defaultValue: "clean three-print magazine spread",
        options: [
          { value: "clean three-print magazine spread", label: "Magazine spread" },
          { value: "simple side-by-side prints on warm paper", label: "Side by side" },
          { value: "family album page with generous margins", label: "Album page" },
        ],
      },
      {
        id: "orientation",
        label: "Page shape",
        type: "select",
        defaultValue: "portrait",
        options: [
          { value: "portrait", label: "Portrait" },
          { value: "landscape", label: "Landscape" },
          { value: "square", label: "Square" },
        ],
      },
      {
        id: "purpose",
        label: "For",
        type: "select",
        defaultValue: "print",
        options: [
          { value: "print", label: "Print" },
          { value: "social media", label: "Social media" },
          { value: "memory album", label: "Memory album" },
        ],
      },
      {
        id: "theme",
        label: "Theme, captions or dates",
        type: "text",
        placeholder: "e.g. summer 2026, quiet captions",
        fallback: "a simple, uncluttered theme",
      },
      {
        id: "title",
        label: "Title",
        type: "text",
        placeholder: "Optional title on the page",
        fallback: "no extra title",
      },
    ],
    mainPrompt:
      "Create a cohesive multi-photo collage using the supplied photographs. Preserve each original photograph and do not alter the people or important details. Arrange the images in a {{layout}} layout with {{theme}} on a {{orientation}} page. Keep the result balanced, attractive and suitable for {{purpose}}. Page title: {{title}}. Quiet paper, even spacing, print-ready. No cartoon stickers or glitter.",
    outputFormat: PRINT_OUTPUT,
  },
  {
    id: "greeting-card",
    category: "print",
    printGroup: "cards",
    name: "Greeting Card",
    shortDescription: "A printable card front from your photograph.",
    icon: "mail",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "occasion",
        label: "Occasion",
        type: "select",
        defaultValue: "birthday",
        options: [
          { value: "birthday", label: "Birthday" },
          { value: "anniversary", label: "Anniversary" },
          { value: "Christmas", label: "Christmas" },
          { value: "thank you", label: "Thank you" },
          { value: "congratulations", label: "Congratulations" },
          { value: "holiday", label: "Holiday" },
          { value: "just because", label: "Just because" },
        ],
      },
      {
        id: "palette",
        label: "Colour palette",
        type: "text",
        placeholder: "e.g. cream and sage, deep red",
        fallback: "a quiet, print-friendly palette",
      },
      {
        id: "decorative",
        label: "Decorative style",
        type: "text",
        placeholder: "e.g. simple botanical, foil-line frame",
        fallback: "a clean, uncluttered card design",
      },
      {
        id: "message",
        label: "Front message",
        type: "text",
        required: true,
        placeholder: "e.g. Happy Birthday Rosie",
      },
    ],
    mainPrompt:
      "Create a beautiful greeting card using the supplied photograph. Preserve the original photograph and important details. Add a {{occasion}} design with {{palette}}, {{decorative}} and the message {{message}}. Keep the layout clean, readable and suitable for sharing or printing. The photograph is the hero image. Quiet typography, generous margin. Not a meme, not a busy scrapbook.",
    outputFormat:
      "Return a single portrait card-front image. The message must be spelled exactly as given. No extra slogans.",
  },
  {
    id: "booth-strip",
    category: "print",
    printGroup: "memories",
    funGroup: "collages",
    name: "Photo Booth Strip",
    shortDescription: "A classic four-frame photo-booth strip.",
    icon: "printer",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Create a classic vertical photo-booth strip of the same person, four frames high, as if taken a few seconds apart with slightly different expressions (neutral, smile, laugh, playful). Black-and-white or slightly warm booth lighting. Thin white borders between frames. Keep identity consistent across all four. No date-stamp gimmicks.",
    outputFormat:
      "Return a single vertical photo-booth strip. Four frames, consistent identity, no extra decoration.",
  },
  {
    id: "travel-postcard",
    category: "print",
    printGroup: "cards",
    name: "Travel Postcard",
    shortDescription: "A postcard from this photograph.",
    icon: "stamp",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "destination",
        label: "Destination",
        type: "text",
        required: true,
        placeholder: "e.g. Moreton, Wirral",
      },
      {
        id: "date",
        label: "Date",
        type: "text",
        placeholder: "e.g. August 2026",
        fallback: "no date",
      },
      {
        id: "styling",
        label: "Postcard style",
        type: "select",
        defaultValue: "vintage",
        options: [
          { value: "vintage", label: "Vintage" },
          { value: "modern", label: "Modern" },
          { value: "illustrated", label: "Illustrated" },
        ],
      },
    ],
    mainPrompt:
      "Turn this photograph into a realistic travel postcard. Preserve the original image and important details. Add a tasteful postcard layout, destination text reading {{destination}}, optional date {{date}}, and {{styling}} postcard styling. Keep the photograph itself natural and recognisable.",
    outputFormat: PRINT_OUTPUT,
  },
  {
    id: "wall-art",
    category: "print",
    printGroup: "cards",
    name: "Wall Art / Canvas",
    shortDescription: "A finished piece ready to hang or print.",
    icon: "frame",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "medium",
        label: "Medium",
        type: "select",
        defaultValue: "canvas",
        options: [
          { value: "canvas", label: "Canvas" },
          { value: "framed print", label: "Framed print" },
          { value: "poster", label: "Poster" },
        ],
      },
      {
        id: "style",
        label: "Style",
        type: "text",
        placeholder: "e.g. quiet photographic, painterly",
        fallback: "a tasteful photographic finish",
      },
      {
        id: "colour",
        label: "Colour treatment",
        type: "text",
        placeholder: "e.g. warm muted, rich colour",
        fallback: "natural colour",
      },
      {
        id: "composition",
        label: "Composition",
        type: "text",
        placeholder: "e.g. generous border, full-bleed",
        fallback: "balanced, print-friendly composition",
      },
    ],
    mainPrompt:
      "Transform this photograph into a finished wall-art design suitable for {{medium}}. Preserve the subject and important details. Apply {{style}}, {{colour}} and {{composition}} while keeping the result tasteful, realistic and suitable for printing.",
    outputFormat: PRINT_OUTPUT,
  },
  {
    id: "photo-calendar",
    category: "print",
    printGroup: "cards",
    name: "Photo Calendar",
    shortDescription: "One month, one photograph, print-ready.",
    icon: "calendar",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "month",
        label: "Month",
        type: "select",
        defaultValue: "January",
        options: [
          { value: "January", label: "January" },
          { value: "February", label: "February" },
          { value: "March", label: "March" },
          { value: "April", label: "April" },
          { value: "May", label: "May" },
          { value: "June", label: "June" },
          { value: "July", label: "July" },
          { value: "August", label: "August" },
          { value: "September", label: "September" },
          { value: "October", label: "October" },
          { value: "November", label: "November" },
          { value: "December", label: "December" },
        ],
      },
      {
        id: "year",
        label: "Year",
        type: "text",
        defaultValue: "2027",
        placeholder: "e.g. 2027",
        fallback: "the current year",
      },
    ],
    mainPrompt:
      "Create a printable calendar layout using the supplied photograph. Preserve the original photograph. Add the month {{month}} and year {{year}}, with a clean, readable calendar design. Keep the photograph and calendar elements balanced and suitable for printing. Days and dates must be correct and readable.",
    outputFormat: PRINT_OUTPUT,
  },
  {
    id: "printable-layout",
    category: "print",
    printGroup: "cards",
    name: "Printable Photo Layout",
    shortDescription: "Margins and size. The photograph stays itself.",
    icon: "ratio",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "size",
        label: "Print size",
        type: "select",
        defaultValue: "6x4 inch print",
        options: [
          { value: "6x4 inch print", label: "6×4 inch" },
          { value: "5x7 inch print", label: "5×7 inch" },
          { value: "8x10 inch print", label: "8×10 inch" },
          { value: "A4 page", label: "A4" },
          { value: "A3 page", label: "A3" },
          { value: "square print", label: "Square" },
        ],
      },
      {
        id: "orientation",
        label: "Page shape",
        type: "select",
        defaultValue: "match the photograph",
        options: [
          { value: "match the photograph", label: "Match the photograph" },
          { value: "portrait", label: "Portrait" },
          { value: "landscape", label: "Landscape" },
          { value: "square", label: "Square" },
        ],
      },
    ],
    mainPrompt:
      "Prepare the supplied photograph as a printable layout for {{size}}. Page shape: {{orientation}}. Preserve the original image and important details. Use appropriate spacing, margins, alignment and proportions. Do not unnecessarily crop or alter the subject.",
    outputFormat: PRINT_OUTPUT,
  },
  {
    id: "album-caption",
    category: "print",
    printGroup: "memories",
    name: "Album Caption",
    shortDescription: "A tasteful caption and date. The photo stays itself.",
    icon: "pencil",
    identityPreservation: "strict",
    version: 1,
    active: true,
    fields: [
      {
        id: "caption",
        label: "Caption",
        type: "text",
        required: true,
        placeholder: "e.g. Moreton garden, May",
      },
      {
        id: "date",
        label: "Date",
        type: "text",
        placeholder: "e.g. 1994",
        fallback: "no date",
      },
    ],
    mainPrompt:
      "Prepare this photograph as an album print with a tasteful caption reading {{caption}} and optional date {{date}}. Preserve the original photograph and the people in it. Place lettering in a quiet margin or beneath the picture, spelled exactly as given. Do not restyle the photograph itself.",
    outputFormat: PRINT_OUTPUT,
  },
];
