import { DEFAULT_OUTPUT } from "./identity";
import type { StyleGroupDefinition, ToolDefinition } from "./types";

export const STYLE_GROUPS: StyleGroupDefinition[] = [
  {
    id: "transfer",
    name: "Style Transfer",
    description: "Describe a look. Keep the same people.",
  },
  {
    id: "photographic",
    name: "Photographic Looks",
    description: "Film, Polaroid and darkroom treatments.",
  },
  {
    id: "artistic",
    name: "Paint, Draw & Illustration",
    description: "Oil, watercolour, pencil, ink and digital.",
  },
  {
    id: "posters",
    name: "Posters & Fine Art",
    description: "Vintage posters and refined black-and-white.",
  },
];

export const STYLE_TOOLS: ToolDefinition[] = [
  {
    id: "style-transfer",
    category: "styles",
    styleGroup: "transfer",
    editGroup: "advanced",
    name: "Style Transfer",
    shortDescription: "Apply a photographic style you describe.",
    icon: "palette",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    example:
      "Transform this image into a 1970s film version. Add soft grain, warm colors, and vintage lens texture. Keep my face recognizable.",
    fields: [
      {
        id: "style",
        label: "Style",
        type: "text",
        required: true,
        placeholder: "e.g. faded 1970s colour print, harsh flash snapshot",
      },
      {
        id: "details",
        label: "Style details",
        type: "text",
        placeholder: "e.g. soft grain, vintage lens texture",
        fallback: "details that suit the chosen style",
      },
      {
        id: "tone",
        label: "Colour tone",
        type: "text",
        placeholder: "e.g. warm amber, cool teal",
        fallback: "a colour tone that suits the style",
      },
      {
        id: "texture",
        label: "Texture",
        type: "text",
        placeholder: "e.g. film grain, smooth paper",
        fallback: "a natural texture for the style",
      },
      {
        id: "subject",
        label: "Main subject",
        type: "text",
        placeholder: "e.g. my face, the garden",
        fallback: "the main subject in the photograph",
      },
      {
        id: "important",
        label: "Important details to preserve",
        type: "text",
        placeholder: "e.g. the expression, the red jumper",
        fallback: "identity, pose and important details",
      },
    ],
    mainPrompt:
      "Render this photograph in the following photographic style, keeping the same people and scene: {{style}}. Transform this image into a {{style}} version. Add {{details}}, {{tone}}, and {{texture}}. Keep {{subject}} recognizable. Do not change {{important}}. It must remain a photograph of the original subject, not a painting unless the style is explicitly a print process.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "colour-film",
    category: "styles",
    styleGroup: "photographic",
    name: "Colour Film",
    shortDescription: "The look of a classic colour negative print.",
    icon: "film",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "stock",
        label: "Feel",
        type: "select",
        defaultValue: "warm 1980s colour negative",
        options: [
          { value: "warm 1980s colour negative", label: "Warm 1980s" },
          { value: "cool 1990s compact-camera print", label: "Cool 1990s" },
          { value: "saturated slide film", label: "Slide film" },
        ],
      },
    ],
    mainPrompt:
      "Give this photograph the look of {{stock}}. Keep the same people, pose and scene. Add authentic film colour, grain and slight print imperfections. Do not add a Polaroid frame unless asked. Do not change faces.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "polaroid-print",
    category: "styles",
    styleGroup: "photographic",
    name: "Polaroid",
    shortDescription: "An instant-print with the classic white frame.",
    icon: "camera",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Render this as a vintage instant Polaroid photograph of the same people and scene. Soft instant-film colours, slight chemical unevenness, classic white Polaroid border. Keep identities. No handwritten caption unless later requested.",
    outputFormat:
      "Return a single Polaroid-framed photograph, centred on a dark surface. No extra collage.",
  },
  {
    id: "darkroom-bw",
    category: "styles",
    styleGroup: "photographic",
    name: "Darkroom Print",
    shortDescription: "A silver-gelatin black-and-white darkroom look.",
    icon: "contrast",
    identityPreservation: "creative",
    version: 1,
    active: true,
    mainPrompt:
      "Make a fine black-and-white darkroom print of this photograph. Preserve identity, pose and composition. Rich silver tones, gentle film grain, slightly warm-black shadows as if selenium toned. No colour. No border. No posterisation.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "oil-painting",
    category: "styles",
    styleGroup: "artistic",
    name: "Oil Painting",
    shortDescription: "Gallery-quality oil paint. Same person, same pose.",
    icon: "paintbrush",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    mainPrompt:
      "Transform this photograph into a realistic oil painting while preserving the subject’s recognisable identity, pose, composition and important details. Use natural brushwork, layered paint texture, believable lighting and a finished gallery-quality appearance.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "watercolour",
    category: "styles",
    styleGroup: "artistic",
    name: "Watercolour",
    shortDescription: "Transparent washes on paper. Keep the scene.",
    icon: "droplets",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    mainPrompt:
      "Transform this photograph into a delicate watercolour painting while preserving the subject, composition and important details. Use natural paper texture, transparent washes, soft edges and realistic colour relationships.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "pencil-sketch",
    category: "styles",
    styleGroup: "artistic",
    name: "Pencil Sketch",
    shortDescription: "Graphite drawing with paper tooth.",
    icon: "pencil",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    mainPrompt:
      "Transform this photograph into a detailed pencil drawing. Preserve the subject’s recognisable identity, pose, proportions and composition. Use realistic graphite shading, line variation and paper texture.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "ink-drawing",
    category: "styles",
    styleGroup: "artistic",
    name: "Ink Drawing",
    shortDescription: "Expressive linework. Identity stays clear.",
    icon: "penTool",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    mainPrompt:
      "Transform this photograph into a detailed ink illustration. Preserve the subject’s recognisable identity, pose and important details. Use expressive linework, controlled shading and a clean illustrated appearance.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "digital-illustration",
    category: "styles",
    styleGroup: "artistic",
    name: "Digital Illustration",
    shortDescription: "A polished illustrated version of this photo.",
    icon: "wand",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    fields: [
      {
        id: "style",
        label: "Style",
        type: "text",
        placeholder: "e.g. clean editorial, storybook, graphic-novel",
        fallback: "a polished contemporary digital illustration style",
      },
      {
        id: "palette",
        label: "Colour palette",
        type: "text",
        placeholder: "e.g. muted earth, bold primaries",
        fallback: "a balanced colour palette that suits the photograph",
      },
      {
        id: "texture",
        label: "Texture",
        type: "text",
        placeholder: "e.g. smooth vector, soft grain",
        fallback: "subtle digital texture",
      },
    ],
    mainPrompt:
      "Transform this photograph into a polished digital illustration while preserving the subject’s recognisable identity, pose, proportions and important details. Use {{style}}, {{palette}} and {{texture}}.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "vintage-poster",
    category: "styles",
    styleGroup: "posters",
    name: "Vintage Poster",
    shortDescription: "Period poster design from this photograph.",
    icon: "ticket",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "period",
        label: "Period or style",
        type: "text",
        placeholder: "e.g. 1930s travel, 1960s gig, Art Deco",
        fallback: "a mid-century travel-poster style",
      },
    ],
    mainPrompt:
      "Transform this image into a vintage poster design inspired by {{period}}. Preserve the subject’s recognisable identity and key details. Use period-appropriate typography, colour, texture, composition and printing imperfections.",
    outputFormat:
      "Return a single poster image. Any lettering must be readable. No watermarks.",
  },
  {
    id: "fine-art-bw",
    category: "styles",
    styleGroup: "posters",
    name: "Fine-Art Black & White",
    shortDescription: "Refined tonal photograph. Not a darkroom reprint.",
    icon: "aperture",
    identityPreservation: "creative",
    version: 1,
    active: true,
    reusable: true,
    mainPrompt:
      "Transform this photograph into a refined black-and-white fine-art image. Preserve the subject and composition. Use sophisticated tonal range, realistic texture, controlled contrast and natural photographic detail.",
    outputFormat: DEFAULT_OUTPUT,
  },
  {
    id: "magazine-cover",
    category: "styles",
    styleGroup: "posters",
    name: "Magazine Cover",
    shortDescription: "A fictional magazine cover using this portrait.",
    icon: "ticket",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "title",
        label: "Magazine title",
        type: "text",
        placeholder: "e.g. NORTH SHORE",
        fallback: "a short original magazine title",
      },
      {
        id: "coverline",
        label: "Cover line",
        type: "text",
        placeholder: "e.g. The quiet garden issue",
        fallback: "one short original cover line",
      },
    ],
    mainPrompt:
      "Create a fictional magazine-cover layout using this photograph as the cover image. Magazine title: {{title}}. Cover line: {{coverline}}. Preserve the person’s recognisable identity. Original typography only — do not copy a real magazine’s masthead or branding. Photorealistic cover photography.",
    outputFormat:
      "Return a single magazine-cover design. Lettering must be spelled exactly as given. No watermarks. Do not imitate a real publication’s logo.",
  },
  {
    id: "record-sleeve",
    category: "styles",
    styleGroup: "posters",
    name: "Record Sleeve",
    shortDescription: "A vinyl LP sleeve from this photograph.",
    icon: "cassette",
    identityPreservation: "creative",
    version: 1,
    active: true,
    fields: [
      {
        id: "artist",
        label: "Artist or title",
        type: "text",
        placeholder: "e.g. Burridge",
        fallback: "an original album title",
      },
    ],
    mainPrompt:
      "Turn this photograph into a square vinyl record sleeve. Title: {{artist}}. Preserve the subject’s recognisable identity. Use print texture, spine-like edge and album-art composition. Original design only — do not copy a real album.",
    outputFormat:
      "Return a single square record-sleeve design. Title spelled exactly as given. No watermarks.",
  },
];
