/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CategoriesIndexRouteImport } from './routes/categories/index'
import { Route as CategoriesCategoryIdRouteImport } from './routes/categories/$categoryId'
import { Route as PhotosIndexRouteImport } from './routes/photos/index'
import { Route as PhotosPhotoIdRouteImport } from './routes/photos/$photoId'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as PromptsPromptIdRouteImport } from './routes/prompts/$promptId'
import { Route as RecipesIndexRouteImport } from './routes/recipes/index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes/$recipeId'
import { Route as ResultsIndexRouteImport } from './routes/results/index'
import { Route as WorkshopToolIdRouteImport } from './routes/workshop/$toolId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryIdRoute = CategoriesCategoryIdRouteImport.update({
  id: '/categories/$categoryId',
  path: '/categories/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosIndexRoute = PhotosIndexRouteImport.update({
  id: '/photos/',
  path: '/photos/',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotosPhotoIdRoute = PhotosPhotoIdRouteImport.update({
  id: '/photos/$photoId',
  path: '/photos/$photoId',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsPromptIdRoute = PromptsPromptIdRouteImport.update({
  id: '/prompts/$promptId',
  path: '/prompts/$promptId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsIndexRoute = ResultsIndexRouteImport.update({
  id: '/results/',
  path: '/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkshopToolIdRoute = WorkshopToolIdRouteImport.update({
  id: '/workshop/$toolId',
  path: '/workshop/$toolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/settings': typeof SettingsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/workshop/$toolId': typeof WorkshopToolIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/settings': typeof SettingsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/workshop/$toolId': typeof WorkshopToolIdRoute
  '/categories': typeof CategoriesIndexRoute
  '/photos': typeof PhotosIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/recipes': typeof RecipesIndexRoute
  '/results': typeof ResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/batch': typeof BatchRoute
  '/settings': typeof SettingsRoute
  '/categories/$categoryId': typeof CategoriesCategoryIdRoute
  '/photos/$photoId': typeof PhotosPhotoIdRoute
  '/prompts/$promptId': typeof PromptsPromptIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/workshop/$toolId': typeof WorkshopToolIdRoute
  '/categories/': typeof CategoriesIndexRoute
  '/photos/': typeof PhotosIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/recipes/': typeof RecipesIndexRoute
  '/results/': typeof ResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/batch'
    | '/settings'
    | '/categories/$categoryId'
    | '/photos/$photoId'
    | '/prompts/$promptId'
    | '/recipes/$recipeId'
    | '/workshop/$toolId'
    | '/categories/'
    | '/photos/'
    | '/prompts/'
    | '/recipes/'
    | '/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/batch'
    | '/settings'
    | '/categories/$categoryId'
    | '/photos/$photoId'
    | '/prompts/$promptId'
    | '/recipes/$recipeId'
    | '/workshop/$toolId'
    | '/categories'
    | '/photos'
    | '/prompts'
    | '/recipes'
    | '/results'
  id:
    | '__root__'
    | '/'
    | '/batch'
    | '/settings'
    | '/categories/$categoryId'
    | '/photos/$photoId'
    | '/prompts/$promptId'
    | '/recipes/$recipeId'
    | '/workshop/$toolId'
    | '/categories/'
    | '/photos/'
    | '/prompts/'
    | '/recipes/'
    | '/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BatchRoute: typeof BatchRoute
  SettingsRoute: typeof SettingsRoute
  CategoriesCategoryIdRoute: typeof CategoriesCategoryIdRoute
  PhotosPhotoIdRoute: typeof PhotosPhotoIdRoute
  PromptsPromptIdRoute: typeof PromptsPromptIdRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  WorkshopToolIdRoute: typeof WorkshopToolIdRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  PhotosIndexRoute: typeof PhotosIndexRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ResultsIndexRoute: typeof ResultsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$categoryId': {
      id: '/categories/$categoryId'
      path: '/categories/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof CategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/': {
      id: '/photos/'
      path: '/photos'
      fullPath: '/photos/'
      preLoaderRoute: typeof PhotosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photos/$photoId': {
      id: '/photos/$photoId'
      path: '/photos/$photoId'
      fullPath: '/photos/$photoId'
      preLoaderRoute: typeof PhotosPhotoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$promptId': {
      id: '/prompts/$promptId'
      path: '/prompts/$promptId'
      fullPath: '/prompts/$promptId'
      preLoaderRoute: typeof PromptsPromptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results/': {
      id: '/results/'
      path: '/results'
      fullPath: '/results/'
      preLoaderRoute: typeof ResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workshop/$toolId': {
      id: '/workshop/$toolId'
      path: '/workshop/$toolId'
      fullPath: '/workshop/$toolId'
      preLoaderRoute: typeof WorkshopToolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BatchRoute: BatchRoute,
  SettingsRoute: SettingsRoute,
  CategoriesCategoryIdRoute: CategoriesCategoryIdRoute,
  PhotosPhotoIdRoute: PhotosPhotoIdRoute,
  PromptsPromptIdRoute: PromptsPromptIdRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  WorkshopToolIdRoute: WorkshopToolIdRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  PhotosIndexRoute: PhotosIndexRoute,
  PromptsIndexRoute: PromptsIndexRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ResultsIndexRoute: ResultsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
